### ISSUE TITLE
opts parameter to wrapFetch is required, but README.md doesn't use

### ISSUE THREAD

**Issue by hakanson** [openzipkin/zipkin-js#11]
The README.md uses this sample code:
`zipkinFetch('http://www.youtube.com/').then(res => res.json()).then(data => ...);`

But with only a `url` parameter, this error appears:
`TypeError: Cannot read property 'method' of undefined`

This appears to be because `wrapFetch.js` assumes the `opts` object exists:
`const method = opts.method || 'GET';`

Assuming the behavior should match`node-fetch`, the documentation is correct and the code implementation should be fixed.

**Comment by sveisvei** [comment]
I agree, we should add default options {} here: https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-fetch/src/wrapFetch.js#L19
