### ISSUE TITLE
zipkin-instrumentation-fetch - get the traceId

### ISSUE THREAD

**Issue by marcelogft** [openzipkin/zipkin-js#111]
Best way to get the generated _traceId_?

Currently is generated inside the **wrapFetch**: 
...
`tracer.scoped(() => {
        tracer.setId(tracer.createChildId());
        const traceId = tracer.id;`

And added as request header: **x-b3-traceid** 
` const zipkinOpts = Request.addZipkinHeaders(opts, traceId);`

But what happens if we want to use that traceId later to access the Zipkin API? for example using _/traces/{traceId}_

I tried with the _recorder_, without success. 

The other way is to rewrite the _wrapFetch_ function and include the _traceId_ when resolving the fetch promise. 
` resolve({response: res, traceId: traceId.traceId});`

Any other options? 

Thanks!

**Comment by siluri** [comment]
i guess `traceid.id.traceid`

**Comment by jcchavezs** [comment]
@marcelogft can we close this issue?

**Comment by marcelogft** [comment]
Yes, you can close it. 
Thank you!
