### ISSUE TITLE
Question: add instrumentation support of koa (HTTP framework)

### ISSUE THREAD

**Issue by shumsky** [openzipkin/zipkin-js#112]
Hi,

Recently I needed to integrate a koa based microservice with zipkin. I didn't find any existing integrations and had to write my custom middleware. Now I'm thinking about contributing it to open source. Would it be reasonable to add corresponding module to zipkin-js/packages?

**Comment by adriancole** [comment]
@vicanso I've seen you have some experience with koa and zipkin. Do
you have any middleware put together like this?

**Comment by vicanso** [comment]
@adriancole  I am not familiar with zipkin and I am not going to write the middleware at this moment.  Sorry for any inconvenience.

**Comment by kohv** [comment]
@shumsky I would be interested. Maybe you could create a PR for this?

**Comment by shumsky** [comment]
@kohv Yes, I'm going to work on it.

**Comment by shumsky** [comment]
Hi,

I'm ready to open a PR. But I've just realized there might be a problem. I've written a middleware for Koa 2.x which requires Node 7 and higher (because of async/await). There are two points.

1. zipkin-js is transpiled to ES2015. This doesn't seem to be a problem, since async-await is transpiled into promises and generators which works fine with Koa 2.x.

2. Travis runs tests on Node 4, 6 and 8. This is an issue. I guess it is not possible to exclude 4 and 6 for my middleware package.

@adriancole maybe you could advise here?

**Comment by davsucks** [comment]
@shumsky Any reason you closed your own PR? I'm in a similar position (needing to orchestrate a koa 2.x.x application) and I'd love to avoid duplicating your effort 😄

**Comment by shumsky** [comment]
Hey @davsucks. I closed it because Travis build was failing and I couldn't figure out how to fix it. I described the problem in my previous comment. Travis build was running tests on different versions of Node including 4 and 6 which are not supported by Koa 2. That was almost 2 years ago and something might have changed since then. I'll try to check this out today/tomorrow.

**Comment by jcchavezs** [comment]
Awesome!

fre. 26. jul. 2019, 13:39 skrev Anton Shumsky <notifications@github.com>:

**Comment by adriancole** [comment]
ps drift alert.. I plan to rewrite the server tests tomorrow similar
to the http client ones
(https://github.com/openzipkin/zipkin-js/pull/427). It should make
implementing this easier.

**Comment by jcchavezs** [comment]
@shumsky currently this library is being tested for node8+ and we got much more solid tests so worth to give it a try.

**Comment by adriancole** [comment]
drift alert is mostly contained, and I'll take responsibility for merge work if later drift affects you

**Comment by shumsky** [comment]
Ok, I've started working on it. Rebased my branch onto the upstream, made some alignments in my code, and then discovered that one of the integration tests is failing. I haven't been working with Zipkin for quite a while, so I guess it may take some time to refresh my knowledge and fix it.

@adriancole thanks for notifying.

**Comment by jcchavezs** [comment]
@shumsky feel free to reach for help in https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
yep if it is in "basic tests" and it is about the post test hook
(which checks for leaks) note that the http server instrumentation
functions leak by default. you need to use scoped to stop that. have a
look at some of the other instrumentation about how that's fixed.

meanwhile we hope to have a non-leaky api eventually

**Comment by shumsky** [comment]
The PR is ready I think. Though I discovered that there's already a package in npm with the same name: https://www.npmjs.com/package/zipkin-instrumentation-koa
I didn't review the existing package in detail. Maybe there's no sense in publishing the module I've written. Or if there is, then it has be renamed at least.

**Comment by adriancole** [comment]
@agreatfool are you ok with us obviating your package? It might be easier on you to have help maintaining this. Otherwise we need to choose a mildly different name like we have done in the past. ex zipkin-instrumentation-koajs

**Comment by agreatfool** [comment]
@adriancole Please give me the maintainer list you guys want to add into the npm package. I will add them, and remove myself immediately you guys confirmed privileges are all OK.

**Comment by jcchavezs** [comment]
@agreatfool awesome. It is enough to add `openzipkin` as maintainer. Really thanks for the collaboration.

**Comment by agreatfool** [comment]
Welcomed :)

Done: 
```
koa-zipkin git:(master) npm owner add "openzipkin" zipkin-instrumentation-koa
+ openzipkin (zipkin-instrumentation-koa)
```

Could you guys please check the privilege. If OK, please notify me, I would remove privilege of myself.

**Comment by jcchavezs** [comment]
I just checked npm and it looks like we have the right access to the package. Thanks a lot @agreatfool this is truly community spirit. I hope you can also jump into this new package as you did a great work in https://github.com/agreatfool/koa-zipkin.

**Comment by agreatfool** [comment]
That's cool. I have removed myself form the npm package. :)
