### ISSUE TITLE
Compatability with non-node environments

### ISSUE THREAD

**Issue by DanielMSchmidt** [openzipkin/zipkin-js#114]
Hey there,

First of all thanks for this great project, it really helps us tracing performance issues in our stack. For the last part of the stack, the react native mobile app, we ran into an issue:

[Zipkin requires](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/InetAddress.js#L1) the package `network-address` to determine the current IP automatically in [`getLocalAddress`](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/InetAddress.js#L23-L25). 

We don't need this functionality, but as the require is on top level we still run into issues, because `network-address` uses the `os` package. This is native to node and not available in the V8 / Safari engine we use.

If we could move the require into the function or migrate to a fallback for non-node environments it would be a lot easier for us. If you agree I would be glad to contribute a PR.

**Comment by adriancole** [comment]
please do. this was an accident I suspect. thanks for raising the issue and
offering help!
