### ISSUE TITLE
Upgrade to kafka-node@2

### ISSUE THREAD

**Issue by SimenB** [openzipkin/zipkin-js#118]
Might want to create a separate transport for people not using zookeeper

**Comment by adriancole** [comment]
agreed. clientOpts currently has the `connectionString` (which is clearly ZK) In other libraries we expose `bootstrapServers`, which is mutually exclusive and hints a more recent version of kafka. 

Assuming library versions would be different, would this mean adding zipkin-transport-kafka10 (which is the first version not requiring ZK for consumers?), or are current kafka libraries backwards compatible (and we instead switch on config property)?

**Comment by SimenB** [comment]
Kafka-node@2 works for 0.8 as well, but the constructor to the clients are a bit different (newer are simplified APIs (just a single object), but that also makes it a bit harder to support both in parallel).

**Comment by SimenB** [comment]
Docs for new client: https://github.com/SOHU-Co/kafka-node/blob/a102a48b3018a11aa479bd7b8a1bcc8599802e22/README.md#kafkaclient
