### ISSUE TITLE
Feature request: async_hooks based context

### ISSUE THREAD

**Issue by SimenB** [openzipkin/zipkin-js#124]
Node 8 has a new async hooks module, which should be able to replace `zipkin-context-cls` entirely, as well as work better (i.e. at all) for promises.

It's still experimental, but not behind a flag. No polyfills exists for older nodes (lots of C++ in the implementation, so probably not incoming either).

https://nodejs.org/api/async_hooks.html

Obligatory hype blog post: https://medium.com/the-node-js-collection/async-hooks-in-node-js-illustrated-b7ce1344111f & 

/cc @sveisvei (https://github.com/openzipkin/zipkin-js/issues/65#issuecomment-268847034)

**Comment by SimenB** [comment]
Might be worth taking a look at a bridge for cls: https://www.npmjs.com/package/cls-hooked

**Comment by SimenB** [comment]
https://www.npmjs.com/package/asyncctx

**Comment by anujshankar** [comment]
https://www.npmjs.com/package/zipkin-context-cls-hooked

**Comment by Ghost---Shadow** [comment]
@anujshankar :)
#201 solves this

**Comment by mziemer21** [comment]
Is there an approach that doesn't use async hooks? There currently are [performance issues](https://github.com/nodejs/benchmarking/issues/181) with async hooks.

**Comment by jcchavezs** [comment]
@mziemer21 not at the moment. Actually this is a good input for this https://github.com/openzipkin/zipkin-js/pull/201#issuecomment-378436554

**Comment by jcchavezs** [comment]
More relevant information: https://github.com/DataDog/dd-trace-js/issues/695
