### ISSUE TITLE
req.header is not a function

### ISSUE THREAD

**Issue by edukondalugorla** [openzipkin/zipkin-js#125]
Hi, I am using  zipkin-instrumentation-express as express js middlewarwe.  I am getting  "req.header is not a function" error.

**Comment by adriancole** [comment]
sorry to hear that. what version of express are you using?

**Comment by edukondalugorla** [comment]
Please find versions

"zipkin-instrumentation-express": "^0.7.3"
"express": "^4.13.3",

**Comment by eirslett** [comment]
Try to console.log the req object? If it comes from express, then req.header should be present; it should be an alias for req.get.
