### ISSUE TITLE
TracerId is set to None when no tracer id is present

### ISSUE THREAD

**Issue by joepuzzo** [openzipkin/zipkin-js#132]
In the index file under `zipkin-js/packages/zipkin/src/tracer/index.js` there is a function called createRoodId. 

This function  generates a traceId with `traceId: None`. According to the zipkin [spec](http://zipkin.io/pages/instrumenting.html) the following should be true. "When an incoming request has no trace information attached, we generate a random trace ID and span ID. The span ID can be reused as the lower 64-bits of the trace ID, but it can also be completely different."

So why is the traceId set to None?

```
createRootId() {
    const id = new TraceId({
      traceId: None, <<<<<<<<< WHY NONE?
      parentId: None,
      spanId: randomTraceId(),
      sampled: None,
      flags: 0
    });
    id._sampled = this.sampler.shouldSample(id);
    return id;
  }
```

**Comment by adriancole** [comment]
this is a historical shortcut when all ids were the same bitlength. If you follow down the rabbithole, it is a shortcut for when the traceId === the spanId
