### ISSUE TITLE
Feature request: Custom timestamps for MutableSpan

### ISSUE THREAD

**Issue by lukiano** [openzipkin/zipkin-js#138]
Currently MutableSpan sets the time when the instance is created as startTimestamp and sets endTimestamp when CLIENT_RECV or SERVER_SEND annotations are set.
I'd like to set custom timestamps in case where I'd like to send a span to the collector, not based on real-time data, but on historical data taken from, let's say, a log.

**Comment by eirslett** [comment]
I think you can override them directly:

```javascript
const span = new MutableSpan()...
doStuff()
span.startTimestamp = something
span.endTimestamp = something
```

**Comment by lukiano** [comment]
True (at least in Javascript, not so much in Typescript), but I'm not actually creating MutableSpan, BatchRecorder is.
I guess I could _extend_ it and override the `record` method

**Comment by eirslett** [comment]
Yup, try doing that and see if it works!

**Comment by lukiano** [comment]
I see the classes from internalRepresentations are not exported: `MutableSpan`, `Endpoint`, Annotation`, etc.

**Comment by adriancole** [comment]
curious.. if you are just recording spans after the fact, would a normal "span" model help? ex one where you set everything at a time, including the name etc?

**Comment by eirslett** [comment]
> I see the classes from internalRepresentations are not exported: MutableSpan, Endpoint, Annotation, etc.

Yes, exporting the internalRepresentations would be kind of an oxymoron... it's only an implementation detail for this client, and could change at any time if we find a better solution.

Is it possible to use the external Span model instead of MutableSpan?

**Comment by lukiano** [comment]
@adriancole I think a normal span model would help.
@eirslett I could just generate the json and send it to the collector, but I'd miss all the great goodness you have on this library

**Comment by adriancole** [comment]
@lukiano so unless someone screams not to, we will end up with a stable model using v2 format #140. Assuming you can run a recent zipkin server, this could work as you can just write the objects from your log files, right? They would look like this:

http://zipkin.io/zipkin-api/#/default/post_spans

**Comment by adriancole** [comment]
@lukiano in zipkin-js 0.10 just out now, you can create a span and upload it like so.. pull request welcome for typescript def on span and endpoint

```javascript
const {
  model: {Span, Endpoint},
  jsonEncoder: {JSON_V2}
} = require('zipkin');
const {HttpLogger} = require('zipkin-transport-http');

const logger = new HttpLogger({
    endpoint: 'http://localhost:9411/api/v2/spans',
    jsonEncoder: JSON_V2
});

const span =  new Span(new TraceId({
  traceId: new Some('000000000000162e'),
  spanId: '000000000000162e',
}));
span.setName('GET');
span.setLocalEndpoint(new Endpoint({
  serviceName: 'PortalService',
  ipv4: '10.57.50.83',
  port: 8080
}));
span.setKind('SERVER');
span.setTimestamp(12312312312312); // epoch micros
span.setDuration(1999); // micros
span.putTag('warning', 'The cake is a lie');

logger.logSpan(span);
```
