### ISSUE TITLE
TypeError: span.toJSON is not a function

### ISSUE THREAD

**Issue by pbadenski** [openzipkin/zipkin-js#147]
This issue gets thrown if a span is being modified (annotation is added) after span has already been finished. Reason is the span will both have `endTimestamp` and would be removed from `partialSpans` in `batch-recorder.js`. This would trigger following sequence of calls (in `packages/zipkin/src/batch-recorder.js`):

```javascript
if (span.endTimestamp) {
  this._writeSpan(id);
```
Source: https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/batch-recorder.js#L48-L49

and then
```javascript
_writeSpan(id) {
  const span = this.partialSpans.get(id); // this.partialSpans.get(id) will return undefined
```
Source: https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/batch-recorder.js#L41-L42

**Comment by eirslett** [comment]
I guess we should discard all span modifications  that happen after endTimestamp has been set - which is when the span is logged, so it's too late to modify it.

**Comment by adriancole** [comment]
>
> I guess we should discard all span modifications that happen after
> endTimestamp has been set - which is when the span is logged, so it's too
> late to modify it.
>
yeah we can either resurrect it (which would end up with a choice as to
whether to flush the late annotation immediately or wait a while) or drop
annotations post finish. Either way we can test it

**Comment by jcchavezs** [comment]
@pbadenski any chance we can come with a PR for either options?

**Comment by jcchavezs** [comment]
@DavideCarvalho @sonybinhle @eirslett @adriancole should we include this in 1.0?

**Comment by adriancole** [comment]
if there's no PR maybe we should close the issue? In general I was hoping a 1.0 would include a design like brave, zipkin-php and zipkin-go which could have a similar approach to this topic.

Either way, reporting data after the fact has two options like mentioned last year :P

**Comment by jcchavezs** [comment]
This might be interesting for your @ghermeto

**Comment by ghermeto** [comment]
@jcchavezs I can pick this one up, but just to be clear, what is the goal here?

On the server side it is hard to imagine a way the user will keep the tracer reference after the request has ended and try to annotate (as all the middleware will only record response at the very end).

During development I do want to know when I mistakenly finished the span prematurely, and in this case fail hard is better. 

Do we want to swallow the error here? I don't think we pass the `logging` library down to the recorder, so that would need to be added to at least let users know that call happened...

thoughts?

**Comment by jcchavezs** [comment]
Legit concerns, I would usually log the error and make it clear that reporting logger should not be used in production (use noop instead). What do you think @adriancole?

**Comment by jcchavezs** [comment]
This might not happen anymore as we now check if the retrieved span is undefined: https://github.com/openzipkin/zipkin-js/blob/aff41209df70502fe8ab09f60a6a0b4a7e4236bd/packages/zipkin/src/batch-recorder.js#L114
