### ISSUE TITLE
Postgres instrumentation

### ISSUE THREAD

**Issue by voldern** [openzipkin/zipkin-js#149]
It would be great to have an instrumentation for [node-postgres](https://www.npmjs.com/package/pg).

Has anyone implemented this privately?

If not I can take a stab at it. The only methods that need wrapping seem to be [pg.Pool.query](https://node-postgres.com/api/pool#pool-query) and [pg.Client.query](https://node-postgres.com/api/client#client-query).

**Comment by adriancole** [comment]
You did a great job. We do have a trend of rule-of-three adding instrumentation.. I wonder if you know any others who would use this? cc @tobespc

**Comment by adriancole** [comment]
we've met rule-of-three. merging!

**Comment by voldern** [comment]
Thanks for the help @adriancole :bowing_man:
