### ISSUE TITLE
equivalent of zipkin-java JsonCodec?

### ISSUE THREAD

**Issue by hakanson** [openzipkin/zipkin-js#15]
zipkin-java has a [JsonCodec](https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/internal/JsonCodec.java) class that is used by things like [ElasticsearchSpanConsumer](https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/java/zipkin/storage/elasticsearch/ElasticsearchSpanConsumer.java) or spring-cloud-sleuth [HttpZipkinSpanReporter](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporter.java).  Can support for JsonCodec be added?

I am looking to leverage the "Spring Cloud Zipkin UI" (not sure of the proper name, but screenshots at https://spring.io/blog/2016/02/15/distributed-tracing-with-spring-cloud-sleuth-and-spring-cloud-zipkin) and this seems like a required prerequisite.

**Comment by eirslett** [comment]
It would be practical, but not strictly needed. This is the way things are connected:

Your application -> Zipkin server -> Backend (e.g. ElasticSearch for Cassandra)

You can also add a queue between, e.g. Your application -> Scribe -> Zipkin server, or Your application -> Kafka -> Zipkin server. If you use the scribe transport, you don't need a queue, you can send span data directly to the Zipkin server on port 9410.

Both the Kafka transport and the Scribe transport depend on Thrift, which is a pretty heavy library; a JSON codec could potentially give us an almost dependency-free transport.

**Comment by hakanson** [comment]
Would a JSON codec also help browser support (a la issue #1)?

**Comment by eirslett** [comment]
It would help for debugging, at least - to have a human-readable message format. (But as I mentioned, it's not a requirement for browser support)

If you want to add it, feel free to send a PR and we'll have a look! :-)

**Comment by hakanson** [comment]
Is JSON codec documented anywhere other that reading the java source code? I was looking for either a spec or an example last week and not having any luck.

**Comment by adriancole** [comment]
the json form is documented here in swagger.. does that help?
http://zipkin.io/zipkin-api/#/paths/%252Fspans

**Comment by sveisvei** [comment]
I would also prefer JSON over http.

**Comment by hakanson** [comment]
It looks like [TraceId](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/tracer/TraceId.js) and [Annotation](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/annotation.js) have implemented `toString` methods that are used by the ConsoleRecorder.   Should the JSON codec be an external class or a set of `toJSON` methods on the objects proper?

Also, after the hint, I found the .yaml behind that Swagge link: https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml

**Comment by eirslett** [comment]
Look at serializeSpan, which currently supports base64 and binary. Also have a look at internalRepresentations. That span is the object that must be serialized.

**Comment by jquatier** [comment]
I actually could use this too, and I'm going to start working on it (unless anyone already has). I have a Spring app that uses the [ZipkinHttpCollector](https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/ZipkinHttpCollector.java) and need to POST the correct JSON to it.

I was planning on making a new `zipkin-transport-http` package that handles translating the spans to the proper JSON format and then sending the spans using `fetch` or `request` to a configurable endpoint. If that sounds good, I also am wondering if I should keep the JSON object translation code in that package or put `toJSON()` methods in the `internalRepresentations` module (similar to the `toThrift()` methods). @eirslett Any thoughts?

Let me know, I'm open to suggestions and I'd like to contribute this back to zipkin-js as a PR when I'm done. Thanks all!

**Comment by eirslett** [comment]
Great initiative! Put the serialization in the same place thrift serialization takes place. (Maybe even add unit tests where it makes sense) We look forward to a PR, thanks a lot!
