### ISSUE TITLE
expressMiddleware.js does not check for the sampled flag

### ISSUE THREAD

**Issue by citrus7** [openzipkin/zipkin-js#152]
I've been having trouble getting sampling and B3 propagation, specifically with the "X-B3-Sampled" header to work with the zipkin-instrumentation-express package.  It seems that regardless of what the sampler is set to or whether or not the incoming request has the X-B3-Sampled header set to 0 the request is logged.  After debugging through the runtime it seems like the the "sampled" flag is being set properly by the library, but the expressMiddleware simply never looks at it.  As a workaround I've wrapped the "recordResponse" methods in an if statement like so:

```
      var id = instrumentation.recordRequest(req.method, formatRequestUrl(req), readHeader);
      if (id.sampled.value) {
        res.on('finish', function () {
          tracer.scoped(function () {
            instrumentation.recordResponse(id, res.statusCode);
          });
        });
      }
```
file in question: https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-express/src/expressMiddleware.js

I wanted to know if this was the intended behavior or if there is a check that happens in another package.  Looking at the zipkin libraries in some other languages there are more obvious checks.

**Comment by adriancole** [comment]
I think the place this logic should be is inside recordResponse() right @pbadenski? Basically any recording should guard internally so that the instrumentation points are cleaner

**Comment by pbadenski** [comment]
Certainly I agree `expressMiddleware` is not abstract enough, but I am also not sure if we might want to push it even farther than `instrumentation`.

I've grepped through the code and currently there doesn't seem to be any checks for sampling - although I'm not 100% sure I'm correctly reading this.

Shouldn't be `sampled` check be as far as `tracer#recordAnnotation`? (or `recorder#record`, but then it's falling onto the implementation to respect the contract).

**Comment by nutchalum** [comment]
Is this the reason that I can't trace an entire request?
I have a proxy in front of every services and all request go through them.

e.g. I have a service A make a request to Service B.
I've expected the output should be one trace with these spans.
span-proxy-A, span-endpoint-A, span-proxy-B, span-endpoint-B

It turns out to be 2 traces instead 
(1) span-proxy-A, span-endpoint-A
(2) span-proxy-B, span-endpoint-B

**Comment by adriancole** [comment]
fixed by https://github.com/openzipkin/zipkin-js/pull/158

**Comment by adriancole** [comment]
>
> Is this the reason that I can't trace an entire request?
> I have a proxy in front of every services and all request go through them.
>
> e.g. I have a service A make a request to Service B.
> I've expected the output should be one trace with these spans.
> span-proxy-A, span-endpoint-A, span-proxy-B, span-endpoint-B
>
> It turns out to be 2 traces instead
> (1) span-proxy-A, span-endpoint-A
> (2) span-proxy-B, span-endpoint-B
>
I don't think this is related

**Comment by nutchalum** [comment]
Yes you are right, that's totally all on me.
My client didn't forward any headers (from incoming) to another proxy(outgoing).

**Comment by citrus7** [comment]
Thanks for the quick turnaround!
