### ISSUE TITLE
Question: Unexpected response while sending Zipkin data, status:404

### ISSUE THREAD

**Issue by pjhampton** [openzipkin/zipkin-js#153]
Hey! Hopefully someone can help me - I am running the example React App.js file from zipking-js-example with the React-Native components removed and I am getting the following error message:

> POST http://localhost:9411/api/v2/spans 404 ()
> Unexpected response while sending Zipkin data, status:404, body: [{"traceId":"d6475f139f32a629","id":"d6475f139f32a629","name":"get","kind":"CLIENT","timestamp":1510178048408000,"duration":294000,"localEndpoint":{"serviceName":"ui"},"remoteEndpoint":{"serviceName":"helloapp"},"tags":{"http.url":"http://localhost:8080","http.status_code":"200"}}]

The upstream is a simple spring boot app which is returning a hello world type message. When I post to http://localhost:9411/api/v1/spans I get no errors, but it doesn't show up in the Zipkin UI. when I post to http://localhost:9411/api/v2/spans I get the above error. Does anybody know what coule potentially be wrong with my implementation?

Thanks in advance!

```
import React from 'react';
import logo from './logo.svg';
import './App.css';

import { Tracer, ExplicitContext, BatchRecorder, jsonEncoder } from 'zipkin';
import wrapFetch from 'zipkin-instrumentation-fetch';
import { HttpLogger } from 'zipkin-transport-http';
const { JSON_V2 } = jsonEncoder;

const zipkinFetch = wrapFetch(fetch, {
  tracer: new Tracer({
    ctxImpl: new ExplicitContext(),
    recorder: new BatchRecorder({
      logger: new HttpLogger({
        endpoint: "http://localhost:9411/api/v2/spans",
        jsonEncoder: JSON_V2,
        fetch,
      }),
    }),
  }),
  serviceName: 'ui',
  remoteServiceName: 'helloapp',
});

class App extends React.Component {

  constructor() {
    super();

    this.state = {
      person: 'Not loaded'
    };

    this.componentWillMount = this.componentWillMount.bind(this);
  }

  componentWillMount() {
    // const randomNumber = Math.floor(Math.random() * 10) + 1;
    // const url = "https://swapi.co/api/people/" + randomNumber;
    
    this.setState(() => {
      return {person: "hello"}
    })

    zipkinFetch("http://localhost:8080").then(res => res.json()).then(data => console.log(data));
  }

  printhello() {
    alert("hello")
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">{this.state.person}</h1>
        </header>
        <button onClick={this.printhello}>Hello!</button>
        <button onClick={this.componentWillMount}>Make request</button>
      </div>
    );
  }
}

export default App;
```

**Comment by eirslett** [comment]
Maybe the version of the Zipkin server is too old, so it only supports /v1/, not /v2/?

**Comment by pjhampton** [comment]
@eirslett Hmm, it's possible. I built the zipkin server off a Spring Boot (1.5.7) application like https://spring.io/blog/2016/02/15/distributed-tracing-with-spring-cloud-sleuth-and-spring-cloud-zipkin

 It's possible that sleuth uses the v1 api and the js instrumentation requires v2.
I will download the Zipkin jar and let you know.

**Comment by pjhampton** [comment]
Hmm, no dice. Weird

**Comment by adriancole** [comment]
so when you do curl -s yourhost:9411/info, it is 2.2.1 and curl -s yourhost:9411/api/v2/services it is 404? probably best to troubleshoot on gitter https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
ps I would use standalone zipkin jar when troubleshooting as opposed to creating your own custom build

**Comment by pjhampton** [comment]
Thanks guys! I have got this fixed.

**Comment by xiaosefengyun** [comment]
when I use kubernetes, i get the same issue,how to solve?

**Comment by jeffthompson1971** [comment]
I have this issue today.  i can GET api/v1/services but cannot POST to api/v1/spans. i get a 404

**Comment by jeffthompson1971** [comment]
Would be great if you posted your fix.. i have same issue.  I get 404 when POST to /api/v1/spans

**Comment by jcchavezs** [comment]
@jeffthompson1971 in this case it was because @pjhampton was using a custom zipkin server (which we don't support). Could you tell us more about your zipkin server setup?
