### ISSUE TITLE
Instrumentation for "got"

### ISSUE THREAD

**Issue by voldern** [openzipkin/zipkin-js#157]
I've created an instrumentation for [got](https://www.npmjs.com/package/got) that can be found here: https://github.com/voldern/zipkin-instrumentation-got.

If enough people are interested and the maintainers think it's a good idea I can move it here.

FYI @sindresorhus

**Comment by jcchavezs** [comment]
@voldern @sindresorhus there is this on-going work for got: https://github.com/openzipkin/zipkin-js/pull/341 thanks to @juhovh

**Comment by juhovh** [comment]
Just for clarification, my version is using hooks that are only available in the latest version, instead of having to rewrite the API in the wrapper as done in the older version above. So in that sense it's much less invasive, but does require a recent version.
