### ISSUE TITLE
Message Send & Message Receive Annotations

### ISSUE THREAD

**Issue by vigneshnrfs** [openzipkin/zipkin-js#161]
hi...

When likely will zipkin-js implement "mr" & "ms" as stated in http://zipkin.io/pages/instrumenting.html ?

**Comment by adriancole** [comment]
this can be added at any time, but as messaging annotations are easy to
misuse, probably best to add instrumentation that needs them. Which
messaging system are you using? Do you have existing work?

**Comment by vigneshnrfs** [comment]
Mine is a custom set up....

I read from kafka. Messages are sent to kafka via a http request (not through kafka producer).

The message is consumed from kafka and it is piped through several nodejs transform streams before it is completed. 

Each of the nodejs streams needs to be instrumented. Currently I am doing "cs" & "cr" to instrument each stream. So each stream process is separate span with parentId as the previous stream span.

What is missing in the instrumentation is the amount of time that it stay in the buffer before another downstream picks it up for processing.

Fairly new to instrumentation and looking at a clean way of doing it.

Also I do batch processing with the streams wherever possible (custom implementation of nodejs transform stream). Chances are at one stream it will be batch processed and in the next subsequent stream it will be processed one at a time. Not sure how do I go about instrumenting this.

Any pointers here would be appreciated. Thanks!

**Comment by adriancole** [comment]
maybe take a look at this for background?
https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-clients

Best way is for us to have a compatible solution.. are you using kafka
0.11+?

On Mon, Nov 20, 2017 at 9:14 AM, Vignesh Jagadeesh <notifications@github.com

**Comment by vigneshnrfs** [comment]
@adriancole Thanks for the background. It would work if all the streams are based on Kafka. 

I agree that we have to have a compatible solution. That way kafka instrumentation can extend the general solution and use it (extracting the header information from kafka 0.11+ headers.) In cases where headers are not available, we would need to expose the same methods (the generalised solution for the developers to extend it).

BTW I am not using Kafka 0.11+

**Comment by adriancole** [comment]
>
> In cases where headers are not available, we would need to expose the same
> methods (the generalised solution for the developers to extend it).
>
so in such case, it is hard to make things compatible, as probably you are
implying an envelope approach, correct? Messaging systems that expose
headers (ex kafka 0.11+ amqp etc) have it easier as you don't need to
coordinate a potentially incompatible wrapper. Wrappers are a pain also
because they can break prod apps in ways harder to do with headers..

**Comment by vigneshnrfs** [comment]
I agree. This would also imply that for users using kafka < 0.11, instrumentation would not be possible.

**Comment by adriancole** [comment]
>
> I agree. This would also imply that for users using kafka < 0.11,
> instrumentation would not be possible.
>
Before, some hijacked message keys. Since kafka keeps moving forward
(already 1.0 now), it might be best to keep < 0.11 custom and not
special-cased in a generic api. For example, we could make a function where
you create your own message wrapper given a trace ID or something..

**Comment by vigneshnrfs** [comment]
Yeah. That makes sense.

**Comment by jcchavezs** [comment]
@vigneshnrfs should we close this issue? Also @jeqo any input on this one?

**Comment by jeqo** [comment]
No much. Agree with Adrian that if using Kafka < 0.11, is better to keep using a custom approach.
But, if using Kafka >= 0.11, what would be the library to instrument? is [kafka-node](https://github.com/SOHU-Co/kafka-node) the *de-facto* library for Kafka or there are other options?

**Comment by jcchavezs** [comment]
Closing this issue for now. Feel free to reopen if any further interest on this.
