### ISSUE TITLE
ScribeLogger using Scribe with ZipkinJS

### ISSUE THREAD

**Issue by cwoodworth** [openzipkin/zipkin-js#17]
I keep receiving the error "ScribeLogger is not a constructor" when I instrument a brand new express application using the sample code provided for the Scribe implementation.  Any help on this would be appreciated.  Relevant code below...

```javascript
//New for Zipkin
const {Tracer, ExplicitContext, BatchRecorder} = require('zipkin');
var zipkinMiddleware = require('zipkin-instrumentation-express').expressMiddleware;
const ScribeLogger = require('zipkin-transport-scribe');

const scribeRecorder = new BatchRecorder({
  logger: new ScribeLogger({
    scribeHost: '127.0.0.1',
    scribePort: 2411,
    scribeInterval: 1
  })
});

var ctxImpl = new ExplicitContext();
//var recorder = new ConsoleRecorder();
var tracer = new Tracer({ctxImpl, scribeRecorder});
//

var app = express();

//Add the Zipkin Middleware
app.use(zipkinMiddleware({
  tracer,
  serviceName: 'zipkinTesting'
}));
```

**Comment by sveisvei** [comment]
Seams there was an typo in the Readme, as `zipkin-transport-script` exports an object with an property `ScribeLogger`.

Correct line 3 to:
```const {ScribeLogger} = require('zipkin-transport-scribe');```

**Comment by cwoodworth** [comment]
That fixed the compilation issues, thanks!  I can see transaction data coming in from two separate services instrumented on localhost port 3000 and port 3001 respectively, but the dependency tree is not displaying.  

One of the services is configured to make a rest API call to get data from the other API service. (e.g. http://localhost:3000/users/getDependencyUsers calls http://localhost:3001/users/get)  Do I need to make any additional changes to enable the dependency data to display?  Let me know if you need specific sample code or configuration information.

**Comment by eirslett** [comment]
You need to use zipkin-dependencies-spark in order to show the dependency tree. (Google it)
Either run it on a Spark cluster, or just java -jar it directly (as a cron job, once every day or so)

**Comment by cwoodworth** [comment]
Thanks for the guidance!  It looks like data is feeding into Zipkin and now Spark is able to run against the DB (Cass @ 2.2.4 as Cass @ 3.5 is unsupported by Spark).
