### ISSUE TITLE
Any plan for supporting async/await?

### ISSUE THREAD

**Issue by sleagon** [openzipkin/zipkin-js#175]
As mentioned in #124 and #135, this package does not work very well in node 8. Is there any schedule for something like zipkin-js@next or zipkin-js 2.x?

**Comment by Fannon** [comment]
+1

**Comment by adriancole** [comment]
some of the related issues are stuck on feedback. anyone want to comment on https://github.com/openzipkin/zipkin-js/pull/135#issuecomment-355870750 ?

**Comment by Ghost---Shadow** [comment]
PR #201 adds this functionality

**Comment by jcchavezs** [comment]
@joepuzzo would you be up for a PR fixing this (of course count us in for
reviews)

Den fre. 14. des. 2018, 16:24 skrev Joe Puzzo <notifications@github.com:

**Comment by joepuzzo** [comment]
So i dont think you want me doing that tbh.. currently the lib uses continuation-local-storage which is the main supported lib.. the cls-hooks version is a fork that sounds like will eventually be merged into the main lib

**Comment by joepuzzo** [comment]
The workaround is simple enough for now.. however one thing i could simply do is provide a second class AsyncCLSContext that was included with lib

**Comment by jcchavezs** [comment]
Addressed by #476
