### ISSUE TITLE
Not compatible with the framework hapi 17.2.0

### ISSUE THREAD

**Issue by ObjectMatrix** [openzipkin/zipkin-js#185]

**Comment by BransonGitomeh** [comment]
hey, great tool here,

is there anything in the works for supporting hapi 17 breaking release?

**Comment by adriancole** [comment]
we need someone to raise a pull request to do this

**Comment by PaulinaStypinska** [comment]
Hey there, I raised a PR for this: https://github.com/openzipkin/zipkin-js/pull/208

just to reiterate my comment from the pr, this is a breaking change for people using hapi v16 and below

**Comment by jcchavezs** [comment]
@fbaiodias do we need this?

**Comment by fbaiodias** [comment]
@jcchavezs we will in the future, but right now we're still on v16 😕

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/250
