### ISSUE TITLE
Possible memory leak, remove listener after promise is resolved

### ISSUE THREAD

**Issue by jemapi** [openzipkin/zipkin-js#186]
Hi,

To prevent memory leaks, the producer listeners (ready, error) should be removed when the connection promise is resolved or failed, this code:

`
...
logSpan(span) {
    this.producerPromise.then(producer => {
      const data = THRIFT.encode(span);
      producer.send([{
        topic: this.topic,
        messages: data
      }], () => {});
    });
  }
...
`

Should be:

`
...
logSpan(span) {
    this.producerPromise.then(producer => {
      const data = THRIFT.encode(span);
      producer.send([{
        topic: this.topic,
        messages: data
      }], () => {});
      producer.removeAllListeners();
    }).catch(err => { producer.removeAllListeners(); });
  }
...
`

Im using the code in a project and when load tested i constantly get:

Error: Too many listeners of type "***-ready" added to EventEmitter. Max is 50 and we've added 51.

**Comment by adriancole** [comment]
thx mind raising a pull request?

**Comment by jemapi** [comment]
Sure, I'll do it

**Comment by ghermeto** [comment]
@jcchavezs looks like this was fixed by https://github.com/openzipkin/zipkin-js/pull/188.

Can you close this?
