### ISSUE TITLE
No microsecond precision on local operation Span timestamps

### ISSUE THREAD

**Issue by jemapi** [openzipkin/zipkin-js#187]
We the hability to get nanoseconds accuracy in the span timestamp, at least for  process running directly on NodeJS, microseconds is not enough for too fast processes. Local process are getting the same timestamp when teir duration in < 1000 microseconds

**Comment by adriancole** [comment]
This has too much impact to change for reasons including that the server
will not be able to understand nanos and most platforms are not accurate to
this either.

**Comment by adriancole** [comment]
If you are recording sub microsecond duration it feels more like profiling
than tracing. Seems to imply you are recording a lot of spans?

Bear in mind that spans are typically used to explain critical path
latency. Several nanos is unlikely to explain a slow request. In the future
if we change the model again, we can certainly reconsider, but for now
especially knowing some are only getting millis accuracy, this seems a bit
too much implied infra work for very few instrumentation that have this
problem.

**Comment by jemapi** [comment]
The problem is that local spans are overlapping its timestamps because these are collected with miliseconds accuracy, if you check the JSON that forms a trace you can see that some of the timestamps (not all) getting it's timestamps in the form NNNNNNNNNNNNN000, thus generating traces like this:

![image](https://user-images.githubusercontent.com/957338/35959472-1a4c5bec-0ca6-11e8-90d4-5fccdff1603a.png)

Even those local spans are executed one after another (via express middlewares)

**Comment by adriancole** [comment]
Ic so this is more about doing better than millis vs doing nanos

**Comment by jcchavezs** [comment]
I think this is a wider issue than the library itself. Maybe worth to discuss it in openzipkin/zipkin if it is really needed. I am closing this for now
