### ISSUE TITLE
Support SamplingFlags extraction?

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#197]
`brave` and `zipkin-php` include the concept of `SamplingFlags` which allows propagation to extract sampling decisions from headers although `trace` information is not there. Shall we support something like that here?

At the moment when such a thing happens, `hapi middleware` fails to extract `traceId`.

Ping @adriancole

**Comment by adriancole** [comment]
If only sampled header doesnt yet work here, then yes indeed it should!
