### ISSUE TITLE
zipkin-instrumentation-express outdated for express-http-proxy

### ISSUE THREAD

**Issue by jonesg504** [openzipkin/zipkin-js#204]
zipkin-instrumentation-express is using removed functions from express-http-proxy and will not work.

functions decorateReq and intercept are removed from the library and replaced with proxyReqOptDecorator and userResDecorator

See: https://www.npmjs.com/package/express-http-proxy

**Comment by DailunCheng** [comment]
I think it's mentioned in #151

**Comment by jcchavezs** [comment]
@epallerols @pchiwan do we need this?

**Comment by jcchavezs** [comment]
Is this still an issue? Ping @ghermeto

**Comment by jcchavezs** [comment]
@jonesg504 does using [connect instrumentation](https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin-instrumentation-connect) fix the issue?

**Comment by jcchavezs** [comment]
I am going to explore this issue next week as I am more familiar with express now.

**Comment by jcchavezs** [comment]
I will close this as duplicated with #151.
