### ISSUE TITLE
Support zipkin server behind a proxy in HttpLogger

### ISSUE THREAD

**Issue by zephinzer** [openzipkin/zipkin-js#205]
**Problem**
We have two networks (let A and B) that can only communicate with each other through a proxy gateway. When specifying the address to the Zipkin server in network B from an application in network A, the HttpLogger is attempting to connect directly without going through the proxy, resulting in a failure to post the trace.

Problem experienced using version `0.12.0` of the `zipkin-transport-http` package using Node v8.10.0 for Ubuntu 16.04.

**Solution**
I am working on implementing the solution outlined in the `node-fetch` repository under [node-fetch Options](https://github.com/bitinn/node-fetch#options) to be able to specify a `http.agent` in the fetch parameter.

**Comment by jcchavezs** [comment]
@zephinzer any update on this one?

**Comment by jcchavezs** [comment]
@zephinzer are you still interested on this?

**Comment by jcchavezs** [comment]
@zephinzer I think this solved this issue, isn't? https://github.com/openzipkin/zipkin-js/pull/439

**Comment by jcchavezs** [comment]
Closing it as I think it was adressed already. Please @zephinzer feel free to reopen if you think it was not addressed.
