### ISSUE TITLE
Collision of traceid when heavily loaded

### ISSUE THREAD

**Issue by jemapi** [openzipkin/zipkin-js#209]
Hi,

We're experiencing collisions of traceId on production when our microservices are heavily loaded, we assume that it's because the traceId is two base64 numbers concatenated, and those are generated with a non-collision-safe algorithm (like uuid).

Will be great that instead of support 64 / 28 bits traces (spans are allways 64), we can gave the implementation (function) to generate the traceId and spanId, this can give more flexibility to the lib. 

If the above is too much complex or doesn't append to the lib logic, then will be great that the traceId / spanId algorithm will be implemented collision-safe to avoid this issues.

Also, UUid is more expensive that what u guys are using, so in terms of performance it should impact.

Let me know your thoughts about it,

Greetings,

**Comment by jcchavezs** [comment]
+1 to avoid collisions with a better algorithm. @jemapi would you come up with a PR exploring a solution?

**Comment by jcchavezs** [comment]
I am closing this issue until we can prove collisions with a test (could be stress test). Feel free to reopen this in such case. Thanks @rcoedo for bringing this up.

**Comment by adriancole** [comment]
Notably, if there is a problem in `randomTraceId()` we should fix it and benchmark it. externalizing isn't a fix. Regardless, we should be very careful about conclusions as in the last few weeks I noticed many scope leak bugs which could appear same as trace collision.
