### ISSUE TITLE
Incorrect TypeScript definition of TraceId

### ISSUE THREAD

**Issue by PhiLhoSoft** [openzipkin/zipkin-js#212]
The current index.d.ts is as follows:
```
  class TraceId {
    _traceId:  option.IOption<string>;
    _parentId: option.IOption<string>;
    _spanId:   string;
    _sampled:  option.IOption<boolean>;
    _flags:    number;

    readonly traceId: string;
    readonly parentId: string;
    readonly spanId: string;
    readonly sampled: option.IOption<boolean>;
    readonly flags: number;

    isDebug(): boolean;

    constructor(args?: {
      traceId?:  option.IOption<string>,
      parentId?: option.IOption<string>,
      spanId?:   string,
      sampled?:  option.IOption<string>,
      flags?:    number
    });
    isDebug(): boolean;
    toString(): string;
  }
```
`isDebug` is defined twice, and the constructor's `args` defines `sampled` as `option.IOption<string>` but I believe it should be `option.IOption<boolean>`.
Beside, I don't think the `_xxx` members should be part of this definition.

**Comment by PhiLhoSoft** [comment]
Also I found two Annotations missing in the Annotation namespace:

    class LocalOperationStart implements IAnnotation {
      constructor(name: string);
      readonly annotationType: string;
      name: string;
    }
    class LocalOperationStop implements IAnnotation {
      readonly annotationType: string;
    }

**Comment by adriancole** [comment]
can you raise a PR to change these things?

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/249
