### ISSUE TITLE
Question: how to add span kind PRODUCER and CONSUMER

### ISSUE THREAD

**Issue by justlaputa** [openzipkin/zipkin-js#215]
Hi,

  I'm using zipkin-js to trace our nodejs applications, but I found there is no way to support async message tracing like RabbitMQ.

  I am aware there is an issue #161 mention this. But the problem is now there is no way even to write customized instrumentation library for messaging tracing, because the js Span model does not support the kind PRODUCER and CONSUMER:

https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/annotation.js#L76

Which is supported in the java brave implementation:
https://github.com/openzipkin/zipkin/blob/master/zipkin2/src/main/java/zipkin2/Span.java#L102

May I ask what is the better approach to implement message tracing in zipkin-js:
1. contribute to this repository, add support for Span kind PRODUCER & CONSUMER
or
2. write my own recorder (instead of using BatchRecorder), and convert 'ms', 'mr' annotation to CONSUMER and PRODUCER span

please correct me if my understanding is wrong.

Thanks!

**Comment by adriancole** [comment]
Regardless, I'd suggest merging in the code similarly done in zipkin-ui
(and tests)
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/spanConverter.js

That said, the v2 model here does actually allow span.kind... v2 style
instrumentation could be made.

**Comment by justlaputa** [comment]
Hi @adriancole thanks for the quick reply. I checked the zipkin-ui project.
I think spanConverter.js is used to convert an v2 span to v1 span.

the v2 model does support span.kind to be PRODUCER or CONSUMER, but the problem is in current zipkin-js, the tracing is added by creating Annotations, then the batch recorder will construct a span depends on the AnnotationType. However now the AnnotationType does not have MessageSent and MessageReceived, which means I can not create a CONSUMER or PRODUCER span without modifying the annotation and batch-recorder code.
https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/batch-recorder.js#L86

Am I right?

**Comment by adriancole** [comment]
yes some code change needs to occur based on the V2 converter rules

**Comment by justlaputa** [comment]
OK I got it. If I want to improve the code for CONSUMER and PRODUCER span, can you give me some suggestion on where to start? Thanks!

**Comment by adriancole** [comment]
For the conversion to work properly into the old model, zipkin-js will need
the following annotation types:

WireSend("ws")
WireRecv("wr")
MessageSend("ms")
MessageRecv("mr")

then, it would need to integrate mapping like here
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/spanConverter.js#L51

This code would affect the same places as you see mappings for SpanKind in
the current code

**Comment by justlaputa** [comment]
Great, thanks for your explanation, I'd like to close this issue and make another one when I have some code ready.

Thanks very much!
