### ISSUE TITLE
Dont add the X-B3-Flags as binary annotation

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#223]
Currently we are annotating the `X-B3-Flags` as a binary annotation but it is a weird behaviour among zipkin clients.

**Comment by adriancole** [comment]
yep especially as flags 0 is meaningless and flags 1 is the same as the
field span.debug=true

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/224
