### ISSUE TITLE
Be explicit with supported node versions

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#231]
At the moment we don't specify what are the node versions supported in package.json nor documentation.

There are implicit versions supported in the Travis file: https://github.com/openzipkin/zipkin-js/blob/master/.travis.yml

**Comment by jcchavezs** [comment]
Is this doable @pchiwan @davesnx @epallerols @fbaiodias @mackermans?

**Comment by davesnx** [comment]
Yes, there's a property on package.json called engines that solves exactly that: https://docs.npmjs.com/files/package.json#engines

**Comment by jcchavezs** [comment]
I think the travis matrix is good enough list for now.
