### ISSUE TITLE
Allow httpServer instrumentation host to be overridden

### ISSUE THREAD

**Issue by rcoedo** [openzipkin/zipkin-js#236]
Currently the httpServer instrumentation implementation is querying the OS to find the host's ip address on every request. This can lead to a performance problem when the server is under heavy load.

![performance](https://user-images.githubusercontent.com/6409659/42496292-d341ba60-8425-11e8-83b3-627601956214.png)

Allowing the host to be overridden is a simple fix for this problem and it wouldn't break the API.

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/237
