### ISSUE TITLE
JSON V2 Tag Value Types

### ISSUE THREAD

**Issue by keitwb** [openzipkin/zipkin-js#243]
According to the Zipkin v2 [JSON swagger spec](https://zipkin.io/zipkin-api/#/), tag values should be strings.  The JSON conversion code here does not convert either numbers or booleans to strings.

If it should do that, I will add it in a separate PR, but wanted to check I'm understanding it correctly.

**Comment by jcchavezs** [comment]
Ping @adriancole @eirslett

**Comment by adriancole** [comment]
yep please do convert to string. We happen to leniently read on our server, but I suspect clones like jaeger, or bridges like skywalking might not leniently coerse to string.

**Comment by jcchavezs** [comment]
@keitwb could you please come up with a PR for this?
