### ISSUE TITLE
addZipkinHeaders return void instead of object

### ISSUE THREAD

**Issue by sonybinhle** [openzipkin/zipkin-js#263]
In the index.d.ts file, the addZipkinHeaders return void
```javascript
namespace Request {
    function addZipkinHeaders(req: {headers: any}, traceId: TraceId): void;
}
```

The actual implementation is the function addZipkinHeaders return a object
```javascript
function addZipkinHeaders(req, traceId) {
  const headers = appendZipkinHeaders(req, traceId);
  return Object.assign({}, req, {headers});
}
```

Same as https://github.com/openzipkin/zipkin-js/issues/190

**Comment by jcchavezs** [comment]
`addZipkinHeaders(req, traceId)` is supposed to return a new request so could you please open a PR changing it?

On the other hand, there is [this issue](https://github.com/openzipkin/zipkin-js/issues/248) that if resolved would avoid such differences.

**Comment by sonybinhle** [comment]
@jcchavezs I would like to create a PR for this issue.
If there is no one work on #248 I would also like to work on it

**Comment by jcchavezs** [comment]
Awesome!

Den fre. 21. sep. 2018, 15:10 skrev Binh Le <notifications@github.com>:
