### ISSUE TITLE
Backfill ts tests for actual implementations.

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#268]
After https://github.com/openzipkin/zipkin-js/pull/264 was merged now we have a way to test implementation to fulfill TS signature. What is missing now is to backfill tests for all packages.

Ping @sonybinhle

**Comment by sonybinhle** [comment]
@jcchavezs Could you please assign this issue to me?

What is the standard PR styles in our project?
For example, I prefer to write the test for about 10 functions at once and file by file.
I mean if I create the PR for this issue, I will divide it into multiple small PRs.

**Comment by adriancole** [comment]
usually we do a PR per task not per file. if all the changes are related I
would raise one pr

**Comment by sonybinhle** [comment]
@adriancole @jcchavezs Thank you very much, so I will raise the PRs per package.
