### ISSUE TITLE
Feature request: zipkin-instrumentation-redis

### ISSUE THREAD

**Issue by SimenB** [openzipkin/zipkin-js#27]
Like https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin-instrumentation-memcached, I suppose 😄

**Comment by eirslett** [comment]
I see you and your feature request, and raise with a pull-request-request! :clubs: :diamonds: :spades: :hearts:

**Comment by SimenB** [comment]
I much prefer being handed features just by asking for them!
I can probably look into it, but I leave on vacation tomorrow, so won't happen for 3 weeks 😄
