### ISSUE TITLE
Update Babel to 7

### ISSUE THREAD

**Issue by DavideCarvalho** [openzipkin/zipkin-js#273]
Since babel is on version 7 now, maybe we could update it.
Babel deps names went from babel-something to @babel/something. This should be a really easy thing to do.

**Comment by jcchavezs** [comment]
Good one. Any chance you start a PR on this?

**Comment by DavideCarvalho** [comment]
I'll make a pr on this when #272 is done

**Comment by jcchavezs** [comment]
Can’t this be done before #272?

José Carlos

**Comment by jcchavezs** [comment]
Awesome!

Den fre. 26. okt. 2018, 21:26 skrev Davi de Carvalho <
notifications@github.com>:

**Comment by jcchavezs** [comment]
I think this is a easier win. We can achiever earlier. What do you think?

Den fre. 26. okt. 2018, 21:37 skrev José Carlos Chávez <jcchavezs@gmail.com

**Comment by DavideCarvalho** [comment]
I thinking changing to Babel 7 should be easier than creating the rollup bundle just because of the ci.

**Comment by jcchavezs** [comment]
Hi @DavideCarvalho,

Did you have time to work on this? Thanks!

Den fre. 26. okt. 2018, 21:47 skrev Davi de Carvalho <
notifications@github.com:

**Comment by DavideCarvalho** [comment]
Sorry, I'm getting ready for a lecture I'm going to do on this saturday morning, so I stopped everything else.
But i've started doind this. I changed the dependency to babel 7, but some tests started to break after I changed - more specifically zipkin-instrumentation-request-promise -

**Comment by jcchavezs** [comment]
Maybe opening the PR would allow us to ping @mkante as they are the one who kindly created this package.

**Comment by mkante** [comment]
@jcchavezs @DavideCarvalho  I will take a look at your PR tonight or tomorrow. Thanks

**Comment by mkante** [comment]
@DavideCarvalho I cloned your branch `DavideCarvalho:feature/rollup-bundle` I didnt see your changes. So far all tests and linter are fine. If you still need my help let me know.

**Comment by jcchavezs** [comment]
This is the PR https://github.com/openzipkin/zipkin-js/pull/277
