### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DavideCarvalho** [openzipkin/zipkin-js#275]
Okay, since i'm creating a bunch of issues, you guys must be thinking why I'm doing this.
zipkin js is one of the few libs on js community to integrate with zipkin. There are even libs on top of zipkin-js.
Since I'm working with zipkin js at work, I stumbled upon some really annoying things, and I wanted to help you to make this lib better and more famous.

Okay, now that you know why I'm doing this, let's get into the roadmap
There are some stuff that I wanted to do, I'll list it here and you guys can make a list of priorities. This way, everyone who comes to help know what needs to be done first. Maybe create a project in this repo os something like it.

- Create bundle with rollup - impediment due node 4.x on CI
  - Create cjs, umd and esm bundles
  - I'm talking about rollup because is one of the most used bundlers for libraries. But there are other alternatives like webpack or parcel.
- Today zipkin js uses babel preset2015. preset2015 is deprecated, but if you guys want it, we can create two bundles, one with preset2015 and another with preset-env.
  - There is a really nice article saying why this is good. [I'll link it here](https://www.smashingmagazine.com/2018/10/smart-bundling-legacy-code-browsers/)
- Upgrade babel 7 - impediment due node 4.x on CI
- Today the code is using a lot of commonjs (like require). Maybe change those requires to import statements
- Use something to type the code. We can use it as documentation, since there are some libs that can create a more technical documentation based on the type defs
  - TypeScript and/or flow
  - PS: Babel 7 can transpile Typescript, so that's a plus
- Create a "human" documentation. With examples that are so simple that people can copy/paste it and it's working.
  - Docusaurus and docisify are good alternatives

**Comment by jcchavezs** [comment]
Thanks a lot for bringing this issue. My two cents:

- Regarding preset2015, I agree the two bundles are good.
- Regarding flow, I think @drolando was interested on using flow in Zipkin JS
- Regarding typescript, @sonybinhle is our TS expert so pinging him here.

All the rest looks good to me. Any input @adriancole?

**Comment by adriancole** [comment]
cc also @abesto

**Comment by adriancole** [comment]
love your plan, Davi.

If you are also interested, we promote sites using zipkin as well. we are
often asked about sites tracing javascript applications. if you are open to
sharing your info here is the template. if you are up to creating a wiki
account ping back and i will give access. you can also take this offline
(well online i guess ;)) on gitter
https://cwiki.apache.org/confluence/display/ZIPKIN/Site+Template

**Comment by adriancole** [comment]
sounds good. you are excellent at being transparent and helping out, Davi

**Comment by jcchavezs** [comment]
Thanks a lot Davi. I think we can close the PR but keep the branch in
bundler. Doing the Babel change sounds better as a short term goal. Thanks
for the willingness to help and the great communication flow.

Den man. 12. nov. 2018, 03:25 skrev Davi de Carvalho <
notifications@github.com:

**Comment by DavideCarvalho** [comment]
Maybe we could use this issue as the roadmap for 1.0, what you guys think?
