### ISSUE TITLE
Drop support for node 4

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#282]
Lately we have been experiencing some blockers in terms of innovation in this library. Mainly because of the incompatibility of node 4 with newer versions of popular libraries (e.g. babel or ts-runtime).

At the beginning we tried to [skip node4 version for some CI jobs](https://github.com/openzipkin/zipkin-js/pull/264/commits/9ca24d264851ac3450b0429a5de10bb66e170e28) but this is something we can't do with dependencies restrictions.

The outcome of this issue should be what is the impact of this breaking change and also to give visibility to 
such a breaking change so potentially affected people can jump into the discussion.

Relates to https://github.com/openzipkin/zipkin-js/pull/264/commits/9ca24d264851ac3450b0429a5de10bb66e170e28, https://github.com/openzipkin/zipkin-js/issues/231, https://github.com/openzipkin/zipkin-js/issues/167, https://github.com/openzipkin/zipkin-js/pull/277#issuecomment-437904076

Ping @DavideCarvalho @eirslett @adriancole @sonybinhle @mkante @pbadenski

**Comment by jcchavezs** [comment]
Agree @DavideCarvalho this is what we did for `ts-runtime` so the idea is the decide whether this overhead is worth or not.

**Comment by eirslett** [comment]
I think we already decided to drop support for Node < 8.
Let's just release version 1.0 which only has support for Node.js 8 and above? We shouldn't be burdened with users running older versions, then they'll have to stay on an old version of zipkin-js or make their own backports.

**Comment by eirslett** [comment]
It's also a duplicate of #146 I guess.

**Comment by basvanbeek** [comment]
Can’t keep on supporting older versions indefinitely at the expense of the project (lost resources). I think being i sync with Node LTS is a good and clear signal to users. I think Node 6 is EOL April next year.

**Comment by eirslett** [comment]
Ok, let's just do it like this.
We stop supporting Node 6 from now on immediately, and then for v1 we only support Node 8+.
 @openzipkin/core Any objections? Does this have to go through any formal Apache voting process, or can we just decide? @michaelsembwever ?

**Comment by devinsba** [comment]
:+1: from me, Node releases seem to have slowed down. I think for sustainability sake making 1.0 based on Node 8 puts things in a good place, not to mention probably makes working on `zipkin-js` more enticing to the community.

I think aligning major versions with Node LTS releases is a good long term strategy, though we should make sure we know our policy for how long we will maintain previous major versions, ie: how long after Node 10 do we maintain `zipkin-js` 1.x?

**Comment by eirslett** [comment]
I suggest that we change supported Node versions for every minor version increase. Then we keep a list of minor releases and corresponding supported Node versions. If anybody needs to run a newer version of zipkin-js on an older version of Node, they will have to take on that burden themselves.

**Comment by jcchavezs** [comment]
Not that I know by heart but we asked it on twitter. I have no access to
GitHub now but maybe the right person to ask is the one who added version 4
in travis.yml file?

Den tir. 13. nov. 2018, 20:31 skrev Eirik Sletteberg <
notifications@github.com:

**Comment by eirslett** [comment]
@rexxars are you still on Node.js 4?

**Comment by DavideCarvalho** [comment]
I agree with @eirslett, keeping up with NodeJS LTS is the best strategy.
I guess someone should create a project, or at least an issue with the roadmap for 1.0, maybe use the already made #275

**Comment by adriancole** [comment]
👍 from me. Incidentally, this project isn't scheduled to go to ASF at the moment.

**Comment by rexxars** [comment]
I'm fine with dropping support for node 4. I generally think that tracking node lts is a good idea.

**Comment by eirslett** [comment]
It's officially decided then. Support for node.js 4 is dropped. I guess this issue can be closed.

**Comment by jcchavezs** [comment]
@eirslett maybe the last thing before closing this issue would be to:
1. remove support from travis
2. upgrade whatever dependency where node4 compatibility was a restriction.

What do you think?

**Comment by eirslett** [comment]
Yup. Let's do it.

**Comment by rexxars** [comment]
Might also want to add the engines field to `package.json`

**Comment by jcchavezs** [comment]
Does this will affect browser usages? (Not a frontend guy)

Den fre. 16. nov. 2018, 07:10 skrev Espen Hovlandsdal <
notifications@github.com:

**Comment by rexxars** [comment]
It might warn if you are using node 4 when running npm install, but given its out of LTS I feel this is perfectly acceptable.

**Comment by jcchavezs** [comment]
Awesome, could any take the ownership of this task (mostly in the part of
see what libraries to upgrade now we dropped node 4). Otherwise I can just
pick it up but probably not have the enough knowledge to upgrade the
libraries.

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 11:06 skrev Espen Hovlandsdal <
notifications@github.com>:

**Comment by DavideCarvalho** [comment]
> @eirslett maybe the last thing before closing this issue would be to:
> 
> 1. remove support from travis
> 2. upgrade whatever dependency where node4 compatibility was a restriction.
> 
> What do you think?

Babel 7 deps are updated #277, only waiting for the merge to be accepted
Node 4 is already dropped from travis
I guess we can close it after babel 7 is merged

**Comment by jcchavezs** [comment]
This is done. Thanks for your participation guys!
