### ISSUE TITLE
AWS KINESIS span transport support 

### ISSUE THREAD

**Issue by jhonatanforero** [openzipkin/zipkin-js#284]
Hi,

Are there any plans to support AWS KINESIS as a span transport? 

Thanks!

**Comment by jcchavezs** [comment]
Hi @jhonatanforero thanks for raising this issue. This project is mainly driven by volunteers so the way we usually work is that we offer direction and help to those users with a feature request so they can do the implementation. Are you up to start such a work?

**Comment by jhonatanforero** [comment]
Yes, I'm Interesting in the functionality because I have a Nodejs Lambda in AWS

**Comment by adriancole** [comment]
fyi this transport exists in the java side in zipkin-aws repo. one decision
to make is keeping here or make zipkin-aws polyglot. probably here...

cc @devinsba @zeagord

**Comment by jhonatanforero** [comment]
Hi @adriancole 

Yes, I  can use the **Zipkin AWS Kinesis collector** from docker image but first I need send the traces with **NodeJs** Lambda. how can I do it? maybe it is a new feature because nodeJs Kinesis transport doesn't exists.

**Comment by adriancole** [comment]
agreed. you would either need to make something yourself based on our kafka
one here, or someone else would :) ideally something like this ends up open
source for others..

**Comment by jcchavezs** [comment]
I think it is easier to have a separated repo for this, so we can have
smaller scope and dedicated documentation but I don't have an strong
opinion at this. It would be also great to have some input from @devinsba
@zeagord.

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 04:33 skrev Adrian Cole <notifications@github.com

**Comment by zeagord** [comment]
I think it is better to have a separate repo with a well defined scope and documentation would be great.  We might start getting requests for other cloud providers as well. It will be maintainable if kept separate.

**Comment by adriancole** [comment]
I would be up for separate repo but maybe not kinesis specific. there are
many aws transports and they have similar needs and libraries.

**Comment by jcchavezs** [comment]
Right, so zipkin-js-aws could be a thing?

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 13:15 skrev Adrian Cole <notifications@github.com

**Comment by adriancole** [comment]
sgtm want the honors of creating it? ;)

**Comment by jcchavezs** [comment]
Of course! @jhonatanforero would you be up to work on this?

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 13:17 skrev Adrian Cole <notifications@github.com

**Comment by jhonatanforero** [comment]
Yes, lets start!

**Comment by jcchavezs** [comment]
Done https://github.com/openzipkin/zipkin-js-aws

José Carlos Chávez


Den lør. 17. nov. 2018 kl. 18:38 skrev jhonatanforero <
notifications@github.com>:

**Comment by jcchavezs** [comment]
@jhonatanforero did you have time to get this started?

**Comment by eirslett** [comment]
Might want to move it to  https://github.com/openzipkin-contrib/ initially?

**Comment by jcchavezs** [comment]
Done, moved to openzipkin-contrib.

José Carlos Chávez


Den ons. 16. jan. 2019 kl. 16:21 skrev Eirik Sletteberg <
notifications@github.com>:
