### ISSUE TITLE
Collaborators list

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#285]
Hi all,

We recently had a lot of great synergy around this project because many amazing developers jumped in. Since it looks like we are going to have [a lot of collaboration coming around v1.0](https://github.com/openzipkin/zipkin-js/projects/1) it would be nice to have a list of frequent collaborators so we can ping them in on important issues and ask for their feedback.

So, please reply with *I am in* if you want to be part of this team: https://github.com/orgs/openzipkin/teams/zipkin-js-champions

Ping @adriancole @mkante @DavideCarvalho @sveisvei @eirslett @sonybinhle @muymoo

PS. This list is not restricted to those one mentioned, it is open for everyone can dedicate time to this library so feel free to ping someone else here.

**Comment by adriancole** [comment]
I am in

**Comment by DavideCarvalho** [comment]
I  am in

**Comment by sonybinhle** [comment]
I am in

**Comment by jcchavezs** [comment]
Ping @briancavalier

**Comment by mkante** [comment]
Im in

**Comment by jcchavezs** [comment]
@DavideCarvalho I added you, you just need to accept the invitation.

**Comment by DavideCarvalho** [comment]
@jcchavezs i haven't received any invitation so for on github, where can I check?

**Comment by jcchavezs** [comment]
@DavideCarvalho just reinvited you. Let me know if you did not receive it by e-mail. I also believe you can see it going to https://github.com/orgs/openzipkin/teams/zipkin-js-champions/members

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/3075074/49131624-2a853c80-f2d9-11e8-9d98-978fbb162a22.png">

**Comment by jcchavezs** [comment]
@davidecarvalho are you on gitter.im?

Den tir. 27. nov. 2018, 22:47 skrev Davi de Carvalho <
notifications@github.com:
