### ISSUE TITLE
Use timestamp of sec instead of now () to set starttimeStamp of Partialspan 

### ISSUE THREAD

**Issue by haoguanjun** [openzipkin/zipkin-js#291]
In function PartialSpan, we set startTimestamp property of PartialSpan to now(), and, in method record of BatchRecorder, we avoid timestamp property of parameter sec, so the start time of the span always fix to now().
By this way, we can't correct send a span that start time does not set to now().
So if we use options.startTime to start a span at special time, It will reset to now().

**Comment by jcchavezs** [comment]
@haoguanjun so to be clear, this is a feature request to be able to pass a start time to a span, isn't?

**Comment by jcchavezs** [comment]
Do you mind opening a PR with such a change? Ping @openzipkin/zipkin-js-champions

**Comment by jcchavezs** [comment]
@haoguanjun are you still interested on this?

**Comment by jcchavezs** [comment]
@haoguanjun this issue was fixed in https://github.com/openzipkin/zipkin-js/commit/3913fd50c6ed9e7a7fce104729bb52b554eaf024 👨‍🚒
