### ISSUE TITLE
Time in microseconds

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin-js#3]
The current implementation in time.js has a bug:

```javascript
const d = new Date();
return d.getTime() * 1000
  + d.getMilliseconds(); // <-- This should be microseconds, not milliseconds
```

We want to get the number of *microseconds* since 1970, not the number of milliseconds. That's why we take d.getTime(), which returns number of milliseconds from 1970, and multiply by 1000, to get number of microseconds since 1970.

In order to solve this, we need to find a timer with microsecond precision, that preferably works both in the browser and in node.js.

**Comment by sveisvei** [comment]
Using https://nodejs.org/api/process.html#process_process_hrtime_time `process.hrtime()` for node.js.

Browsers is another thing, and does not have this implemented yet. (https://www.w3.org/TR/hr-time/)
There is a shim we can use: https://github.com/kumavis/browser-process-hrtime

**Comment by jdarling** [comment]
This might help, it uses process.hrtime if its available, if not it falls back to new Date.getTime

```js
const counter = (function(){
  if(process && process.hrtime){
    var getNanoSeconds = function(){
      var hr = process.hrtime();
      return hr[0] * 1e9 + hr[1];
    };
    var loadTime = getNanoSeconds();
    return function(from){
      var v = (getNanoSeconds()-loadTime) / 1e6;
      return from?v-from:v;
    };
  }
  return function(from){
    var v = (new Date()).getTime();
    return from?v-from:v;
  };
})();
```

This way if you have any values past the . you know you have higher precision values available.  If not then you still have the milli's that you can utilize.

**Comment by adriancole** [comment]
Thanks for the help, folks. I might try something including these tips.

**Comment by adriancole** [comment]
heh I just discovered that browser-process-hrtime isn't quite right as it returns relative seconds not epoch ones https://github.com/kumavis/browser-process-hrtime/issues/4 cc @basvanbeek

**Comment by adriancole** [comment]
got a bit distracted today, but made heavy progress. I will have this done tomorrow

**Comment by adriancole** [comment]
fix https://github.com/openzipkin/zipkin-js/pull/51
