### ISSUE TITLE
Autopublish merges into master as canaries

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#316]
Currently, releasing is a manual process, not often and error prone. It is very likely changes in configuration can break the process without further notice. Releasing every canary would fix that problem.

See https://github.com/lerna/lerna/tree/master/commands/publish#--canary

Ping @openzipkin/zipkin-js-champions

**Comment by DavideCarvalho** [comment]
We should not use master canary releases. Master should only publish when we have a pack of changes ready to be publish as a stable version.

Instead of using Master for that, we should create a “develop” branch and use it for that. Why develop? See gitflow https://zellwk.com/blog/git-flow/

**Comment by eirslett** [comment]
I disagree, I don't think having a separate develop branch and a "release-only" master branch is a good idea. Git tags serve the purpose of identifying which commits are release commits. I think every commit on the master branch should be released as a canary. So :+1:

**Comment by ghermeto** [comment]
would be much appreciated. 👍

**Comment by adriancole** [comment]
sounds fine to me as long as versions do sensible things. master should always be working though there is some big change with typescript coming up so common sense should apply on when to merge things knowing the canary stuff. (ex increment version before huge change)

**Comment by devinsba** [comment]
I agree with the canaries from master idea, if only because it aligns this repo with the rest of the org, in that releases are done on tag and master is the most up to date snapshot

**Comment by DavideCarvalho** [comment]
I don't agree. Master should have the latest stable version. Usually, when using gitflow, canary releases are released on develop branch.

**Comment by eirslett** [comment]
i think the Zipkin core server is released as a snapshot/canary on every commit/merge to master, is that still the case @adriancole ? That worked pretty well.

It's true that with gitflow uses a develop branch and a separate master branch: I'm against using gitflow at all, because we don't need the value it provides in exchange for extra complexity. I prefer canary releases from master, and stable releases on git tags. (Only my 2c though)

**Comment by jcchavezs** [comment]
Thanks everyone for the feedback. My thoughts on this:

I think adding canaries for release provide many benefits:
1. Exercise the release process.
2. Publish non stable tags so people could try stuff and shorten the
feedback loop before we provide a proper release.

That does not mean we encourage people to use this canary releases (if
someone wants to use it is at its own risk).

In the other hand, using different branches is something inconvenient from
my POV:
1. It causes that changes are integrated later and that cause massive
rebases (think that zipkin-js is not something people work on every day, as
a volunteering project, people work on it when they have time). The sooner
we integrate changes into master, the better and the easier for everyone.
Again, not every single master merge triggers a release so we have a buffer
of time if something wrong gets merged.
2. Dealing with one branch is already complex, I think managing two will be
hard too.
3. Having one branch is simple and easy for getting people on board.
Imposing something like gitflow requires people to get use to that.

In particular, I don't think having master as the latest stable commit is a
requirement, I would say having tags is good enough for people to use.

José Carlos Chávez


Den ons. 12. des. 2018 kl. 14:00 skrev Eirik Sletteberg <
notifications@github.com>:

**Comment by adriancole** [comment]
>
> i think the Zipkin core server is released as a snapshot/canary on every
> commit/merge to master, is that still the case @adriancole
> <https://github.com/adriancole> ? That worked pretty well.
>
haha if it did no idea!

>

**Comment by devinsba** [comment]
Hmm, maybe we should publish server snapshots to bintray? If we don't then I rescind my recommendation that we should publish canaries, I will leave that up to the Node ecosystem folks

**Comment by jcchavezs** [comment]
I think it is reasonable to say we want this. Is anyone in the mood to start this work? @landons @ghermeto @sonybinhle maybe?

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/451
