### ISSUE TITLE
Should TraceId be set to express req.headers or res.locals if it's empty at the beginning?

### ISSUE THREAD

**Issue by kenspirit** [openzipkin/zipkin-js#318]
According to issue https://github.com/openzipkin/zipkin-js/issues/88, express middleware doesn't seem to be able to work well to capture following middleware's operation's span especially if it involves async/await/Promise work.

When in expressMiddleware, it starts `instrumentation.recordRequest` and generated one id, would it be more helpful for the developers to deal with different scenarios if it's set into the req.headers or res.locals so that they can pick up the context in later middleware in order to be enclosed in the same trace as child span?

**Comment by jcchavezs** [comment]
Hi there! Thanks for coming by. I am not sure I understand the issue, is
the idea to be able to access the span of the express middlewares is to add
some sort of customisation? If that is the case the zipkin idiomatic way to
do so is the spanCustomizer (not implemented here yet).

Could you please provide an example of the use case you are referring to
here?

Den ons. 12. des. 2018, 06:53 skrev Ken Chen <notifications@github.com:

**Comment by kenspirit** [comment]
@jcchavezs I am not sure what spanCustomizer is, but I think the idea is to access the span created by the zipkin expressMiddleware.

As in current expressMiddelware's implementation, the id generated in it by `instrumentation.recordRequest` is not setting in req or res.locals, it merely record the whole response after it's done.

the `next()` call in that middleware indicates the next middleware to move on so that the processing pipeline can do the work.  But if followup middlewares can not access the id first generated by the zipkin express middleware, and there are some async/await/Promise usage in the followup middlewares, I cannot use zipkin-context-cls to help capture the trace and span to build the hierarchy for me.

I have to pass around the traceId or context myself for a particular request.  There is no guideline or docs available on how it can be achieved in zipkin-express for this too.

**Comment by kenspirit** [comment]
BTW, I don't quite understand why step 2 in below sample code cannot be able to get the parentId "14c2b283477a12a9" as the step 1, and it's creating a new one "e2844c87b3354fec"?

```javascript
const express = require('express');
const { Tracer, ExplicitContext, ConsoleRecorder } = require('zipkin');
const zipkinMiddleware = require('zipkin-instrumentation-express').expressMiddleware;

const ctxImpl = new ExplicitContext();
const recorder = new ConsoleRecorder();
const localServiceName = 'service-a'; // name of this application
const tracer = new Tracer({ ctxImpl, recorder, localServiceName });

const app = express();

// Add the Zipkin middleware
app.use(zipkinMiddleware({ tracer }));

async function step1() {
  return tracer.local('Step 1', () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('Step 1 Done');
      }, 1000);
    });
  });
}

async function step2() {
  return tracer.local('Step 2', () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('Step 2 Done');
      }, 2000);
    });
  });
}

app.get('/ping', async (req, res) => {
  await step1();

  await step2();

  res.send('pong');
});

app.listen(9999);
```

The capture span is like below:

```bash
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): ServiceName("service-a")
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): Rpc("GET")
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): BinaryAnnotation(http.path="/ping")
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): ServerRecv()
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): LocalAddr(host="InetAddress(10.0.75.1)", port=0)
Record at (spanId=ca3cf3659a79f393, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): ServiceName("service-a")
Record at (spanId=ca3cf3659a79f393, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): LocalOperationStart("Step 1")
Record at (spanId=ca3cf3659a79f393, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): LocalOperationStop()
Record at (spanId=e2844c87b3354fec, parentId=e2844c87b3354fec, traceId=e2844c87b3354fec): ServiceName("service-a")
Record at (spanId=e2844c87b3354fec, parentId=e2844c87b3354fec, traceId=e2844c87b3354fec): LocalOperationStart("Step 2")
Record at (spanId=e2844c87b3354fec, parentId=e2844c87b3354fec, traceId=e2844c87b3354fec): LocalOperationStop()
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): BinaryAnnotation(http.status_code="200")
Record at (spanId=14c2b283477a12a9, parentId=14c2b283477a12a9, traceId=14c2b283477a12a9): ServerSend()
```

**Comment by ghermeto** [comment]
hi @kenspirit, 

I can reproduce the issue with `zipkin-instrumentation-express`. I also tested the same with `zipkin-instrumentation-connect` and, using that one, both the `traceId` and `parentId` remains constant, while the `spanId` changes during the asynchronous calls: 

```javascript
const express = require('express');
const { Tracer, ExplicitContext, ConsoleRecorder } = require('zipkin');
const zipkinMiddleware = require('zipkin-instrumentation-connect');
const request = require('superagent');

const ctxImpl = new ExplicitContext();
const recorder = new ConsoleRecorder();
const localServiceName = 'service-a'; // name of this application
const tracer = new Tracer({ ctxImpl, recorder, localServiceName });

const app = express();

// Add the Zipkin middleware
app.use(zipkinMiddleware({ tracer }));

async function step1() {
    return tracer.local('Step 1', () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('Step 1 Done');
            }, 1000);
        });
    });
}

async function step2() {
    return tracer.local('Step 2', () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('Step 2 Done');
            }, 2000);
        });
    });
}

app.get('/ping', async (req, res) => {
    await step1();

    await step2();

    res.send('pong');
});

const server = app.listen(9999, () => {
    request.get('http://localhost:9999/ping')
        .end(() => server.close());
});
```

produces:

```
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): ServiceName("service-a")
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): Rpc("GET")
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): BinaryAnnotation(http.path="/ping")
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): ServerRecv()
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): LocalAddr(host="InetAddress(192.168.1.19)", port=0)
Record at (spanId=11e4470b22b9bd48, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): ServiceName("service-a")
Record at (spanId=11e4470b22b9bd48, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): LocalOperationStart("Step 1")
Record at (spanId=11e4470b22b9bd48, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): LocalOperationStop()
Record at (spanId=6a1494c8288ec052, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): ServiceName("service-a")
Record at (spanId=6a1494c8288ec052, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): LocalOperationStart("Step 2")
Record at (spanId=6a1494c8288ec052, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): LocalOperationStop()
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): BinaryAnnotation(http.status_code="200")
Record at (spanId=01efef49a5fefde3, parentId=01efef49a5fefde3, traceId=01efef49a5fefde3): ServerSend()
```

I believe that is the correct behavior. @jcchavezs please correct me if I'm wrong.

**Comment by kenspirit** [comment]
@jcchavezs in zipkin-connect, it contains what I expected to have in zipkin-express

```javascript
Object.defineProperty(req, '_trace_id', {configurable: false, get: () => id});
```

@jcchavezs @ghermeto I don't know why the express and connect middleware are behaving differently.  Is it because in express middleware, it's wrapped in a `scoped` function call?

**Comment by ghermeto** [comment]
@kenspirit yes, I create PR #319 to solve this issue and added the tests to verify it

**Comment by kenspirit** [comment]
@ghermeto Just saw that.  Thanks.  I wonder if you can add below statement like the one in zipkin-connect into the PR also:

```javascript
Object.defineProperty(req, '_trace_id', {configurable: false, get: () => id});
```

And honestly, I don't understand exactly why extra scope causes the problem.  The scope function should be finished already because the `next()` call is there and control should be already passed to next middleware.  Why the spanId can be inherited in step1 but not step2.

**Comment by ghermeto** [comment]
@kenspirit I updated the PR to add that line.

AFAIK promise chains will lose the scope...
