### ISSUE TITLE
Typo in 0.16.0 github release name

### ISSUE THREAD

**Issue by briancavalier** [openzipkin/zipkin-js#326]
I just noticed that the 0.16.0 release name on [github releases page](https://github.com/openzipkin/zipkin-js/releases) says "1.6.0".  This is just a typo in the name, though, so it likely hasn't caused any real problems other than some double-takes :)

The git tag, [package.json](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/package.json#L3) and [npm published version](https://www.npmjs.com/package/zipkin) all seem to be correct (0.16.0), but it was confusing for a minute when I happened to look at the github releases.

Hopefully a quick name edit will fix things up.  Cheers, and thank you for your continued work on zipkin-js!

![screen shot 2019-01-16 at 11 39 32 am](https://user-images.githubusercontent.com/90518/51264159-d9fa9900-1983-11e9-9282-aed7567cea17.png)

**Comment by jcchavezs** [comment]
Sorry for this. My fault. I just fixed it :).
