### ISSUE TITLE
Should httpServer instrumentation assumes sampled header always provided with spanId?

### ISSUE THREAD

**Issue by kenspirit** [openzipkin/zipkin-js#327]
In HttpServerInstrumentation, the logic of creating traceId when header contains x-b3-spanid and x-b3-traceid assumes that the x-b3-sampled headers are also provided.

https://github.com/openzipkin/zipkin-js/blob/9e0eee22a07156056656c2eeca8b4f94d5dbed34/packages/zipkin/src/instrumentation/httpServer.js#L47

the value of `sampled` is actually `None` when we are using the `readHeader` function provided from `zipkin-instrumentation-connect` middleware.

Then it results in that the traceId created by `zipkin-instrumentation-connect` middleware will always not captured.

Should the `None` value be directly used here?  Would it be better if it has similar logic when calling `tracer.createRootId` without parameters, which calls the `sampler` to decide?

The issue raised here is that the Pivotal Cloud Foundry which has Zipkin enabled only injected those three ids header without the sampled header.

https://docs.pivotal.io/pivotalcf/2-4/concepts/http-routing.html#http-headers

**Comment by adriancole** [comment]
if there is no sampled header but valid trace and span id, then a sampling
decision should be made.

I think what I just wrote agrees with you!

**Comment by jcchavezs** [comment]
@kenspirit thanks for rising this issue. So if no sampled header is present, tracer should use sampler to make a decision. In this specific case, sampler is making the decision when creating the span but not when using an extracted one.

As far as I understand, [connect middleware calls instrumentation.recordRequest](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-connect/src/middleware.js#L56) which calls (tracer.id)[https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/tracer/index.js#L163] and I think here it is when tracer should make the decision. Are you up to raise a PR for this with a test included?

Ping @ghermeto

**Comment by kenspirit** [comment]
Thanks @adriancole and @jcchavezs for supporting this opinion.

@jcchavezs, I can try to raise PR for the change.  But shouldn't the decision be made in HttpServer?

https://github.com/openzipkin/zipkin-js/blob/9e0eee22a07156056656c2eeca8b4f94d5dbed34/packages/zipkin/src/instrumentation/httpServer.js#L47

When detecting the `sampled` is None, then it can call `this.tracer.sampler` to do some work.  Do you think that it's not good to access sampler using this kind of chain call to expose inner logic?

The L163 you mentioned is tracer's generic call to obtain an id, I think it would not be an appropriate place?

**Comment by kenspirit** [comment]
PR https://github.com/openzipkin/zipkin-js/pull/328 submitted

**Comment by jcchavezs** [comment]
So the thing is that accessing directly to object properties is leaking
knowledge about them. I don't think we should access to it. Any thoughts
@adriancole?

Den tir. 12. feb. 2019, 02:34 skrev Ken Chen <notifications@github.com:

**Comment by adriancole** [comment]
> So the thing is that accessing directly to object properties is leaking
> knowledge about them. I don't think we should access to it. Any thoughts
> @adriancole?
>
some of the logic is a bit mixed anyway, for example creating IDs if not
present. I don't completely follow which decisions are where, though I have
an opinion that extracting from headers should ideally be separate from ID
generation and sampling logic.

**Comment by kenspirit** [comment]
From my point of view, the sampling logic (use sampler to make the decision while the sampled header is missing) should be in HTTPServer instrumentation or Tracer.  Not the id getter in tracer.

If the logic resides in instrumentation, it needs to know the sampler.
If the logic in Tracer, we should not directly new a TraceId in instrumentation as it has no sampler knowledge there.

We can either expose an API from Tracer to produce the TraceId (when sampled is None, then pass to sampler to make the decision) or expose the sampler directly.

The `createChildId()` in tracer seems has the right logic but what we need now is another `createRootId()` with `spanId`, `traceId` and other parameters passed in?

**Comment by adriancole** [comment]
Since it sounds like you are up to refactoring, I think we should consider doing just that!

when sampling is probabilistic only, agreed the tracer can handle it. In brave we have a function called "joinSpan" which handles the backfilling of sampling status as needed.

here's the call site.. note that here we "attempt" to employ an http layer sampler (one aware of http path expressions)
https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpServerHandler.java#L84

**Comment by kenspirit** [comment]
@adriancole I think the logic under below condition is just doing the backfilling similarly?  Do you mean we move this logic (L43 - L63) into tracer?

https://github.com/openzipkin/zipkin-js/blob/9e0eee22a07156056656c2eeca8b4f94d5dbed34/packages/zipkin/src/instrumentation/httpServer.js#L42

**Comment by adriancole** [comment]
basically separate out the header extraction from acting on the data. the
header extraction can result in a TraceId object representing the inbound
call. A tracer function named join or similar can look at that and backfill
if possible the sampling status (TraceId.sampled can hold a None value, so
the tracer logic can re-use that). I suspect the same logic would be
re-used in the grpc server handler also.

**Comment by kenspirit** [comment]
@adriancole agree with you.  I moved the traceId backfilling & sampled value calculation to tracer.join method.  Please review the new commit in PR and see if that is what you prefer.

**Comment by ghermeto** [comment]
@jcchavezs sorry I am late to the party, but I looked at #328 and it seems the right approach. 

Also, changing `zipkin-instrumentation-connect` would fix only that particular instrumentation and the problem would remain for the others... looks like Express and Restify instrumentation also will set `sampled` to `None`
