### ISSUE TITLE
Cannot set rootId

### ISSUE THREAD

**Issue by vmakarevich** [openzipkin/zipkin-js#332]
can someone explain to me how can I manually chain traces, f.e. I have one server request and inside call some other external endpoints, how can I bind all external calls to one server call? In koa I want smth like create one traceId for each api server call and in controller have access to it and assign as parent for other calls, like 
```
middleware(ctx, next) {
ctx.rootCtxTraceId = tracer.id;

return next()
}
in controller (ctx, next) {
//don't know how but here I need to create new id and bind it to root (ctx.rootCtxTraceId)
// and pass further
httpcall(url, headersWithNewTraceIdBindedToRootId)
}
```
Actually the main trouble of this library is understandability, we have cls, wrapper for zipkin, zipkin and zipkin-instrumentation, if your logic is little bit complicated rather then get/create headers and send it to server, you spend a lot of time to understand because you need to read all code

**Comment by jcchavezs** [comment]
Hi @vmakarevich, I think this is what you are looking for: https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin-context-cls.
