### ISSUE TITLE
Drop support for node 6

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#338]
Support for node 6 [is going to end on April 2019](https://nodejs.org/en/about/releases/). We should consider drop support for that after that happens.

There is an ongoing work on this matter: https://github.com/openzipkin/zipkin-js/pull/146

Ping @openzipkin/zipkin-js-champions

**Comment by jcchavezs** [comment]
Ping @ghermeto

**Comment by jcchavezs** [comment]
Duplicated https://github.com/openzipkin/zipkin-js/pull/146

**Comment by jcchavezs** [comment]
Related to https://github.com/openzipkin/zipkin-js/pull/250

**Comment by ghermeto** [comment]
👍 on it

**Comment by eirslett** [comment]
👍 This will also let us default to using async hooks instead of continuation-local-storage.

**Comment by jcchavezs** [comment]
So what are the actions we could take on this one? I think the first step is to remove node 6 from travis (I can do that). Could you @ghermeto and @eirslett create (or give visibility) to those actions that we could start?
