### ISSUE TITLE
I want tracking of module inside same microservices also?

### ISSUE THREAD

**Issue by awesomehimanshu** [openzipkin/zipkin-js#342]
Let say i have 3 microservice

I can track interaction of those microservices by fetch , but i want the time taken from one function to other . Let say.

1. I have a mysql call , then file read , then file write in same microservice. I want to track time taken by this three also in the span.

Is it possible ? If possible can you tell . I don't find any blog or documentation in repo too.

**Comment by jcchavezs** [comment]
It is possible but you need instrumentation for each one. There is one
community instrumentation for MySQL:
https://github.com/juspay/zipkin-instrumentation-mysql but for file IO you
might need to write your own or look for an existing one.

Den lør. 2. mar. 2019, 20:06 skrev Himanshu sharma <notifications@github.com

**Comment by jcchavezs** [comment]
For further questions please join us on gitter.im/openzipkin/zipkin :).

Den lør. 2. mar. 2019, 20:10 skrev José Carlos Chávez <jcchavezs@gmail.com>:

**Comment by awesomehimanshu** [comment]
Ok sure . That means if i want to instrument anything i want its instrument libaray in node.js ?

**Comment by jcchavezs** [comment]
Yes, exactly that. We provide some instrumentations for different kind of
components. You can find some of them at
https://zipkin.io/pages/tracers_instrumentation and there are some other
community ones.

Den søn. 3. mar. 2019, 06:38 skrev Himanshu sharma <notifications@github.com
