### ISSUE TITLE
Allow customization of the message sent in recordRpc (express-middleware)

### ISSUE THREAD

**Issue by DavidGarNav** [openzipkin/zipkin-js#361]
Hello! At the moment, message sent in recordRpc is a combination of `req.method` and `req.route.path` as can be seen here:
https://github.com/openzipkin/zipkin-js/blob/aeb5d09beaa3b3dd634200625f236c76ea4630d0/packages/zipkin-instrumentation-express/src/expressMiddleware.js#L58

It would be a great improvement to allow the customization of this message.
Maybe through a method passed as an argument of expressMiddleware function (like tracer, servicename and port). This method could accept `req` object as argument to have access to properties like `req.originalUrl` or `req.baseUrl`
With this improvement examples like this could be achieved.

```javascript
const customMessage = function customMessage(req) {
     return 'Custom message: '.concat(serviceName, ' ').concat(req.method, ' ')
     .concat(req.baseUrl).concat(req.route.path);
};
// Add zipkin middleware
app.use(zipkinMiddleware({ tracer, serviceName, customMessage }));
```

Thanks in advance.

**Comment by jcchavezs** [comment]
I am not sure about the example. It looks too much information that could get to the point of redundancy (serviceName and baseURL sounds redundant to me but I don't fully know the use case). That said, in some http frameworks we have the concept of `spanCustomizer` which is a very simple interface that receives a request and allows users to customize the span based on it. See https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/SpanCustomizer.php for a reference.

Do you feel like implementing it?

Ping @adriancole @ghermeto

**Comment by ghermeto** [comment]
I'm not sure about this idea. I need to first understand why would we need to customize the Rpc for an HTTP server.

**Comment by DavidGarNav** [comment]
Thanks for your responses @jcchavezs and @ghermeto. I will try to explain the need to customize the Rpc.

Our API framework does not allow us to include the whole endpoint inside `req.route.path` in consequence we are not able to distinguise two endpoints from two different services in Zipkin.

Lets say:

-  Service 1:
    - method = post
    - originaUrl = api/servcie1/get
    - req.baseUrl = api/service1
    - req.route.path = /add

- Service 2: 
    - method = post
    - originaUrl = api/servcie2/get
    - req.baseUrl = api/service2
    - req.route.path = /add

With the actual behaviour of express-middleware `recordRpc` method will send the same message for both services (`post /add`). If we want to apply metrics based on this field both services will be considered the same, which is a mistake.
Unfortunately recode our routing system to avoid this problem is not possible, that's why we request this change.

I can't see how the `spanCustomizer` could help to solve this problem becuse if `recordRpc` method is not replaced, the same message will be sent anyway.

A possible implementation of the change that we request could be:
Add `customMessage ` argument to
https://github.com/openzipkin/zipkin-js/blob/aeb5d09beaa3b3dd634200625f236c76ea4630d0/packages/zipkin-instrumentation-express/src/expressMiddleware.js#L30

Result:
```javascript
module.exports = function expressMiddleware({tracer, serviceName, port = 0, customMessage = null}) {
```

Replace code inside if statement at
https://github.com/openzipkin/zipkin-js/blob/aeb5d09beaa3b3dd634200625f236c76ea4630d0/packages/zipkin-instrumentation-express/src/expressMiddleware.js#L57-L59

Result:
```javascript
if (req.route) {
    if (customMessage) {
        tracer.recordRpc(customMessage(req));
    } else {
        tracer.recordRpc(`${req.method} ${req.route.path}`);
    }
}
```

I hope that this explanation helps to understand our request.

Thank you

**Comment by adriancole** [comment]
drive by comment: http.route is the tag name we typically use to identify
the route path you discuss.

**Comment by jcchavezs** [comment]
It makes sense to me @DavidGarNav, I would just change the code into:

`tracer.recordRpc(spanNamer(req))` where the default namer is `req.route`.

That said I **strongly discourage you** to use a high cardinality like a raw path.

**Comment by DavidGarNav** [comment]
Thank you @jcchavezs 
I appreciate it.

> That said I strongly discourage you to use a high cardinality like a raw path.

I'll keep it in mind.

**Comment by jcchavezs** [comment]
Could we close this one @DavidGarNav

**Comment by DavidGarNav** [comment]
Go ahead @jcchavezs

**Comment by jcchavezs** [comment]
Awesome @DavidGarNav!
