### ISSUE TITLE
Add flush to HttpLogger

### ISSUE THREAD

**Issue by CSP197** [openzipkin/zipkin-js#362]
I want to use zipkin-js to trace requests handled by an AWS lambda function, written in NodeJS but the lambda seems to be dropping the request context prior to the async POST call to my Zipkin collector.

Currently, I'm using the ExplicitContext attribute from zipkin-js and the lambda function dies before the reporter can send the span.

I suspect the AWS Lambda drops the request context immediately after receiving the response, and since the reporter sends the POST request to the collector on a 1 sec cadence, the reporter is unable to send the span data.

A possible resolution may be to make the reporter synchronous (i.e: block the thread until the span is reported, and only then finish the request).

And another possible resolution may be to add a flush option, which would ideally asynchronously close the POST http request to the Zipkin collector, prior to finishing the request and the lambda shutting down.

Any advice is appreciated 👍

**Comment by jcchavezs** [comment]
I believe this is a legit request. Do you feel like coming up with a PR?

**Comment by CSP197** [comment]
I'm happy to try, but I'm fairly new to javascript and its versatile syntax... :)

As I currently understand it, the processQueue function in HttpLogger.js on line 85 defines the fetch POST request to the Zipkin collector and the timer object on line 45 actually calls processQueue function at an interval (defined by the httpInterval variable).

My approach would be to add an optional Boolean variable named flush to the HttpLogger constructor, followed by an if/else statement in the setInterval function of the timer object. If the flush variable is present, then the setInterval will run on the interval of 0 milliseconds, otherwise it will default to the httpInterval value.

I'm not sure how to make the make the instrumentation wait for the request to complete as the POST request is asynchronous..

**Comment by jcchavezs** [comment]
What about passing -1 to the interval when you want to do the manual flushing? This way, on `-1` the interval is never triggered and then you can flush it manually? Ping @adriancole

**Comment by adriancole** [comment]
regardless you will need to add a function on httplogger to flush it
synchronously (or a close method, I'm not sure what is semantically
correct). We are discussing a lot more than the work of adding a function
for either. Can someone take on and just do  this?

**Comment by jcchavezs** [comment]
Preparing a release today @CSP197

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-js/releases/tag/v0.18.6
