### ISSUE TITLE
Same SpanID, ParentID and TraceID in every span in different services

### ISSUE THREAD

**Issue by 21stio** [openzipkin/zipkin-js#38]
Hi, 

I just dived into Zipkin and it's really cool so far. But I couldn't get it running perfectly. 
To test the interaction I set up two express Server in docker and one is calling the other.

However, both servers emit the same Span information SpanID, ParentID and TraceID. Is that an intended behaviour, a bug or did I screw something up? 

Is the Service that creates the root span (in this case `watch_1`)  supposed to have a ParentID?

(`watch_1` calls, `fetchme_1` responds )
<img width="1137" alt="screen shot 2016-08-29 at 16 46 26" src="https://cloud.githubusercontent.com/assets/17232576/18055461/375f18c0-6e08-11e6-9b5c-509e7a2b6627.png">

If the environment variable FETCH_URL is set it will act as the caller otherwise it will just respond to queries.

```typescript
import * as express from "express";

var fetch = require('node-fetch');
const {trace, BatchRecorder, Tracer, ExplicitContext, ConsoleRecorder} = require('zipkin');
const zipkinMiddleware = require('zipkin-instrumentation-express').expressMiddleware;
const {HttpLogger} = require('zipkin-transport-http');
const CLSContext = require('zipkin-context-cls');

var ctxImpl = new ExplicitContext();
var recorder = new ConsoleRecorder();

const tracer = new Tracer({
    recorder: recorder,
    ctxImpl: new CLSContext('zipkin')
});


//CALLER
const wrapFetch = require('zipkin-instrumentation-fetch');

const zipkinFetch = wrapFetch(fetch, {
    tracer,
    serviceName: process.env.SERVICE_NAME + '-fetch-' + process.env.APPLICATION_PORT,
    port: process.env.APPLICATION_PORT
});

if (process.env.FETCH_URL != undefined) {
    setTimeout(function () {
        zipkinFetch(process.env.FETCH_URL).then(function (res) {
            return res.text();
        }).then(function (body) {
            console.log(body)
        });
    }, 1000)
}

var app = express();


//RECEIVER
app.use(function (request:express.Request, response:express.Response, next) {
    console.log(request.headers);

    next()
});

app.use(zipkinMiddleware({
    tracer,
    serviceName: process.env.SERVICE_NAME + '-middleware-' + process.env.APPLICATION_PORT,
    port: process.env.APPLICATION_PORT
}));

app.use('/', function (request:express.Request, response:express.Response, next) {
    response.send('Hi');
});





app.listen(process.env.APPLICATION_PORT, function () {
    console.log('The PetStore sample is now running at http://localhost:' + process.env.APPLICATION_PORT);
});
```

Thanks in advance :)

**Comment by eirslett** [comment]
That's correct behavior. When you have only one span, all the ids in the trace will be the same. There are two services/nodes (I'll call them nodes, since not all points in the graph have to be services) here, but only one span, because a span represents the interaction between two nodes.
If you introduce a third node, for example a web browser, which calls the first service, then there will be two spans in the trace.

**Comment by adriancole** [comment]
Great explanation, Eirik

**Comment by 21stio** [comment]
Ah awesome, got it, thanks :) 

However, the Zipkin UI span detail does not seem as expressive as imagined to me. Intuitively I would have expected the root span to be the top span. Right now the only way to see what's the root service is by looking at the url or opening the top span.
<img width="1471" alt="screen shot 2016-08-30 at 10 47 52" src="https://cloud.githubusercontent.com/assets/17232576/18082445/48b3ab58-6e9f-11e6-9ddd-c2818ac2520f.png">

Also the metadata of the spans are emitted twice. 
<img width="956" alt="screen shot 2016-08-30 at 10 48 00" src="https://cloud.githubusercontent.com/assets/17232576/18082456/4db2968c-6e9f-11e6-8764-4f021bad6313.png">

I can totally live with both, I just want to make sure that it's the intended behaviour. Can you confirm that? 

Btw, it's an awesome tracing solution, happy I came across!

**Comment by adriancole** [comment]
mind posting your example? or modifying this?
https://github.com/openzipkin/zipkin-js-example/pull/1

You should see a root span, for sure..

**Comment by eirslett** [comment]
Usually, you would see a setup like this:

browser -> front-facing webapp -> microservice 1 -> microservice 2 -> database

Then, the root span would be "front-facing webapp" in the Zipkin UI. So even if the trace is triggered by the browser, the span starts at the first service.

**Comment by 21stio** [comment]
Hey,

I ran another test I finally understood how it's working. The service that will be hit first is the root span even if the service that triggers the request itself is traced. 

root service is root span
Browser -> root service -> child_one -> child_two 

child_one is root span
root service -> child_one -> child_two

Thanks a lot guys! :)
