### ISSUE TITLE
add 'zipkin-js.flush' annotation when data is kicked out

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-js#381]
We have `finagle.flush` and `brave.flush` to know when data is kicked out vs intentionally sent incomplete. We should add `zipkin-js.flush` when data is kicked out on timeout as otherwise it can be really hard, if possible, to tell that was the case.

**Comment by CSP197** [comment]
@adriancole @jcchavezs - Would https://github.com/openzipkin/zipkin-js/issues/362 be related to this issue?

**Comment by adriancole** [comment]
this is more about when the batchlogger automatically flushes data. I think you are asking in #362 to manually flush it. Usually when manual flushing happens we don't add an annotation (though a user could choose to do so)
