### ISSUE TITLE
Add configurable logger

### ISSUE THREAD

**Issue by jquatier** [openzipkin/zipkin-js#41]
There are a couple places where we use console logging for errors where it would be good if you could pass in a logger to use instead of `console.error`. We can still default to console logging if that's desired, but in a lot of cases I think users will already have a logger they want to use. Should be fairly easy to implement. Examples would be in `HttpLogger` or `ScribeLogger`.

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/294
