### ISSUE TITLE
defaultTags is missing from the core zipkin Tracer constructor in index.d.ts?

### ISSUE THREAD

**Issue by jeffthompson1971** [openzipkin/zipkin-js#413]
I'm trying to simply use the contructor of the Tracer to pass the defaultTags.  I see it's there but the type file is missing it so my typscript compile fails

All I do to make this work is add 'defaultTags' to the Tracer constructor in index.d.ts

 class Tracer {
    constructor(args: {
      ctxImpl: Context<TraceId>,
      recorder: Recorder,
      sampler?: sampler.Sampler,
      supportsJoin?: boolean,
      traceId128Bit?: boolean,
      localServiceName?: string,
      localEndpoint?: model.Endpoint,
      log?: Console,
      **defaultTags?: any,**
    });

Can you guys add that please?

**Comment by adriancole** [comment]
mind raising a pull request. I will merge it for ya!

**Comment by jeffthompson1971** [comment]
will do!

**Comment by jcchavezs** [comment]
Release is out: https://github.com/openzipkin/zipkin-js/releases/tag/v0.18.5
