### ISSUE TITLE
 It would be great if there is es5 equivalent of this project 

### ISSUE THREAD

**Issue by byteshiva** [openzipkin/zipkin-js#44]
it would be nice if there is a es5 equivalent of this project. I have converted this entire project to es5 using babel. but not tested completely.

https://github.com/byteshiva/zipkin-js-es5

It would be helpful, to run this project on version below  node 4.1.0 or something above 0.10.35

**Comment by sveisvei** [comment]
We could publish with an es5/node 4 version. PR welcome for adding a buildstep that does this.

**Comment by eirslett** [comment]
+1 for @sveisvei's solution

**Comment by byteshiva** [comment]
I have made some changes on zipkins and thrift changes to make it work in es5/v0.10.35, Here is the gist https://gist.github.com/byteshiva/f717fb364ef0dd3f2c09ebb61da90a6d

**Comment by adriancole** [comment]
I think this is a dupe of #16 please re-open if not
