### ISSUE TITLE
Express Middleware child trace/span

### ISSUE THREAD

**Issue by daveking999** [openzipkin/zipkin-js#444]
I have an authentication process - REST call where I could like to add custom traces (or Spans) inside the lifecycle of this request, so I can see the entire request span and its child components.
I'm using zipkin-js.
I have tried tracer.local and tracer.scoped - all to no avail.
I can see the trace in the logs but it's not attached to the parent (express/REST) call.
Here's a verbose example - i have tried a few combinations, this is the latest.

```
tracer.scoped(() => {
        const msg = 'Authentication Started 2';
        Sdk.logger('Parent: ' + originalTraceId);
        const id = tracer.createChildId(originalTraceId);
        tracer.setId(id);
        Sdk.logger('Child: ' + tracer.id);
        tracer.recordBinary('Reason', msg);
        tracer.recordAnnotation(new annotation.Message('Authentication Started 2'));
        Sdk.logger(tracer.id + ' - ' + msg);
    });
```

The parentSpanId is not getting set:
```
Parent: TraceId(spanId=29655379c7b2a3e2, parentSpanId=None, traceId=29655379c7b2a3e2)
Child: TraceId(spanId=fe890a61e19b2c53, parentSpanId=None, traceId=fe890a61e19b2c53)
```

Am I doing something incorrect?
This was easily achieved in Spring/Java by creating a new Span but the doc & example for the js client is not so extensive.
Many Thanks !

**Comment by jcchavezs** [comment]
Hi Dave,

I will come back to this by Sunday.

tir. 3. sep. 2019, 12:15 skrev Dave King <notifications@github.com>:

**Comment by jcchavezs** [comment]
Hi @daveking999 it is better to do such questions on gitter: https://gitter.im/openzipkin/zipkin.

I am not sure what could be issue but I recommend you open a PR with the test case so it would be easier for us to triage it.
