### ISSUE TITLE
License File missing in build output

### ISSUE THREAD

**Issue by Patrick-Spiegel** [openzipkin/zipkin-js#478]
The output for the zipkin packages is missing the license file. 

![image](https://user-images.githubusercontent.com/35311793/73926928-c7c20480-48d0-11ea-9ee2-24d5155a4bcf.png)

**Comment by jcchavezs** [comment]
Yeah, as far as I see this is implemented in
https://github.com/lerna/lerna/pull/1465 so it is a matter of on what
version of Lerna solves this problem. Even more, maybe we have that version
already (PR was merged 1 year ago) and we just need to do a new release (we
did not with latest change in licensing).

Are you up to do that check or upgrade Lerna version accordingly
@Patrick-Spiegel?

tor. 6. feb. 2020, 11:07 skrev Patrick Spiegel <notifications@github.com>:

**Comment by Patrick-Spiegel** [comment]
I have upgraded the lerna version but the used version was released 8 months ago.

**Comment by jcchavezs** [comment]
i had some issues (not sure related to lerna 3.20 or not) but in any case I moved to 3.16.x which was the version that introduced this feature. This is fixed now: https://registry.npmjs.org/zipkin/-/zipkin-0.19.2.tgz
