### ISSUE TITLE
With the new portal UI it doesn't let you search by spanName anymore?

### ISSUE THREAD

**Issue by jeffthompson1971** [openzipkin/zipkin-js#482]
My spans all have names, but the dropdown in the UI shows 'no options' and does not let you fill it with a string manually.   
<img width="1071" alt="Screen Shot 2020-02-06 at 10 54 25 AM" src="https://user-images.githubusercontent.com/2018750/73959556-1a9abc80-48cf-11ea-83a2-1488baec5971.png">

**Comment by jcchavezs** [comment]
Hi @jeffthompson1971 I believe before you select the spanName you should select the serviceName. In any I don't think this is an issue on this library. UI issues should be reported in openzipkin/zipkin repo but I suggest you first ask such things on gitter.
