### ISSUE TITLE
We should probably update the README to talk about browsers

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-js#54]
The README focuses on node, but we do actually work on browsers. Maybe we could revise some things and suggest browserify (if that's a decent recommendation).

**Comment by adriancole** [comment]
suppose we should also link the example to the README, too https://github.com/openzipkin/zipkin-js-example

**Comment by jcchavezs** [comment]
Closed by https://github.com/openzipkin/zipkin-js/pull/312
