### ISSUE TITLE
BatchRecorder expects ServerAddr annotation to be InetAddress

### ISSUE THREAD

**Issue by narqo** [openzipkin/zipkin-js#58]
`record` method of BatchRecorder has [a piece of code][1], that tries to cast the `host` field of the annotation to integer, using `rec.annotation.host.toInt()` of your `InetAddress` class. 

It seems `ServerAddr` annotation constructor doesn't have any opinion about `host` parameter, so this behaviour mightn't be expected. 

For example, the `zipkin-instrumentation-redis` provides an example, which uses host as a raw string both for connection options and for remote server annotation:

```
const redisConnectionOptions = {
  host: 'localhost',
  port: '6379'
};
const redis = zipkinClient(tracer, Redis, redisConnectionOptions);
```

Shouldn't `BatchRecorder` cast host field of `ServerAddr` annotation to integer (ipv4/ipv6 address) during the recording process?

[1]: https://github.com/openzipkin/zipkin-js/blob/d446c82b962c33a98f134585d29c590b3707119f/packages/zipkin/src/batch-recorder.js#L110-L115

**Comment by eirslett** [comment]
That's right; we need to convert it to an IP address. Maybe we have to do a DNS lookup?

**Comment by narqo** [comment]
I think the question is which component must be responsible for this conversion: Annotation, Recorder, or InetAddress?

**Comment by eirslett** [comment]
It would make sense to do it in InetAddress.
But DNS lookup is async, so it can potentially be quite hairy...

**Comment by adriancole** [comment]
pragmatically, I'd probably do anything that does dns lookup up-front, and then re-use the result as the server address, or sneak into redis code and pull the actual ip from there.

**Comment by narqo** [comment]
I can't be 100% sure, but it doesn't feel that making a call to the system's `getaddrinfo` (which is underneath the `dns.lookup()`) is an operation that one must care so much. Having a local DNS cache might bring much more troubles. And looks like every net socket connection does `dns.lookup` anyway.

It'd be much more intuitive if `BatchRecorder` dealt with host-to-ip conversion by itself. I think it shouldn't be hard to implement. The thing that must be changed is `BatchRecorder#record()` which makes span updating synchronously. I'll try to provide a draft PR so we can discuss the exact details.

**Comment by adriancole** [comment]
bear in mind I think this is really a special case we are looking at for redis. the wrong data was placed into a field. Adding responsibility at BatchRecorder is probably not a right fit even if an easy answer.

**Comment by adriancole** [comment]
in other words, let's try to solve this at the right abstraction, wherever that is.

**Comment by adriancole** [comment]
taking a peek, here's my 2p on this..

* BatchRecorder isn't the only path, so probably better to solve this in the actual record types
* ServerAddr and LocalAddr don't inspect the contents to see if the host is an address or just a string etc.

It might be best for BatchRecorder to not attempt to coerce to an int (which assumes ipv4). In other words, simply pass the input fields directly to the Endpoint constructor (delegating such logic there).

At that point, we have centralized logic in the internalRepresentations Endpoint. That way it is solved regardless of Local Server (or Client) address. This is a good place as it is near where the data is used, too. For example, "host" isn't ever sent to zipkin, rather the ipv4 or ipv6 address derived from it. Moreover, tests there can be made to check the known things we can coerce from.. in one place.

thoughts?

**Comment by narqo** [comment]
> It might be best for BatchRecorder to not attempt to coerce to an int (which assumes ipv4). In other words, simply pass the input fields directly to the Endpoint constructor.

I totally agree. By saying that `BatchRecorder#record` should be changed, I mostly meant that this is a place that could be made async, without harming the whole API. The exact coercing might be done in a sort of "fabric" function, that would asynchronously return a proper instance of the `Endpoint` (believe me, you don't want to make the class constructor itself async :))

**Comment by narqo** [comment]
For me, `makeEndpoint()` of [zipkin-go-opentracing](https://github.com/openzipkin/zipkin-go-opentracing/blob/master/zipkin-endpoint.go) is the solution that do things properly. We only need to port it to node.js.

**Comment by adriancole** [comment]
I'm not implying the conversion happens in the Endpoint constructor.. I
didn't mean to say that if I did. I said blindly pass what was given you to
the constructor. It just needs to be addressed sometime before it is
reported/logged. By centralizing the concern to sometime between getting
Endpoint and it being converted to json or thrift, we solve it all three
cases of endpoint vs whack-a-mole.

None of this says "how" you do it, you can certainly use a function like
that.. just saying it should be done close to the problem (in
internalRepresentations.js where other conversion is occurring). You'll
notice that the marshalling of json/thrift is off the critical path right
now anyway (as it is called for the logger/reporter impls), so your async
concern is ok, right? Fancier scheduling than that could be deferred, imho,
and would apply to things that aren't just dns.

does this make sense?

**Comment by adriancole** [comment]
ps I suspect status quo is breaking things? should we just delete that entry temporarily? for example, zipkin works fine without ServerAddr, so if spans are being dropped we might want to tactically patch and release (like now) until the PR that addresses this for all is in.

**Comment by jcchavezs** [comment]
This does not seem to be an issue anymore as per in https://github.com/openzipkin/zipkin-js/blob/aff41209df70502fe8ab09f60a6a0b4a7e4236bd/packages/zipkin/src/batch-recorder.js#L238. Closing it. @narqo feel free to reopen it if you have further concerns.
