### ISSUE TITLE
Span durations appear to be incorrect for hapi.js middleware

### ISSUE THREAD

**Issue by zackangelo** [openzipkin/zipkin-js#61]
Lengthy requests exceeding several seconds are being reported as 1-2ms. 

Wrote a failing test here: https://github.com/zackangelo/zipkin-js/blob/fix_hapi_span_duration/packages/zipkin-instrumentation-hapi/test/integrationTest.js#L157

Has anyone else noticed this? If so, or seems entirely possible, will open a PR to fix.

**Comment by adriancole** [comment]
haven't noticed, but you are right we don't have reality check test on duration. Assuming the indexes in the test are correct, then that implies the following either isn't the right hook or it isn't being invoked asynchronously (or something else)

```
      response.once('finish', () => {
```

**Comment by eirslett** [comment]
Maybe we are mixing micros and millis somewhere?

**Comment by zackangelo** [comment]
According to [the request lifecycle docs](https://github.com/hapijs/hapi/blob/master/API.md#request-lifecycle), the current hook we're using (`onPreResponse`) executes after the request has been processed.
