### ISSUE TITLE
Windows build, yet again

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin-js#72]
Looks like the prepublish script (for babel) doesn't work on Windows... we need to have a look at porting it so that it works on all platforms. (I think it should be possible to release zipkin-js from a Windows machine if needed)

**Comment by eirslett** [comment]
@tonypizzicato do you have access to a Windows machine to debug a little bit on?

**Comment by muymoo** [comment]
The AppVeyor build is currently failing on:
```
npm run lerna-bootstrap
> zipkin-js@ lerna-bootstrap C:\projects\zipkin-js
> node node_modules/lerna/bin/lerna.js bootstrap
Lerna v2.0.0-beta.30
Bootstrapping 12 packages
Installing external dependencies
Symlinking packages and binaries
Prepublishing packages
Errored while running BootstrapCommand.execute
Error: Command failed: npm run prepublish 
'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! zipkin@0.5.1 build: `../../node_modules/.bin/babel src -d lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zipkin@0.5.1 build script '../../node_modules/.bin/babel src -d lib'.
```

Some ideas: 
- Lerna requires you to add binary devDependencies to each package:

> Note that devDependencies providing "binary" executables that are used by npm scripts still need to be installed directly in each package where they're used.
https://github.com/lerna/lerna/blob/master/README.md#common-devdependencies

Add `babel-cli` as dependency to each packages' package.json. Change `../../node_modules/.bin/babel src -d lib` to `babel src -d lib`

- This is a open issue with npm: https://github.com/npm/npm/issues/13789
- Yarn also had the same issue recently: https://github.com/yarnpkg/yarn/pull/2617

**Comment by rexxars** [comment]
I had a look at this in #82 - most tests are running now. Check out that PR for more details on what is currently failing.

**Comment by rexxars** [comment]
Tests seem to be passing in #82 now.

**Comment by rexxars** [comment]
And now in master :-1: 
Should be able to close this now.
