### ISSUE TITLE
Configurable sample rate 

### ISSUE THREAD

**Issue by nickcodefresh** [openzipkin/zipkin-js#75]
In my Spring Cloud Sleuth library I can set a sample resolution for zipkin integration (e.g. 10% of spans are published per instance). Can this library be configured in a similar way? 

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/README.adoc

**Comment by adriancole** [comment]
unlike sleuth, this project doesn't assume a specific configuration library. So, when you configure the library, you'd choose how to specify things like the sample rate. Example of wiring up is here:

https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin

Moving forward, I don't know what the status quo configuration tools are for browser or node apps. It may be the case that such libraries will turn-up, similar to how dropwizard-zipkin was made in java to bind dropwizard-style config on top of brave.

**Comment by huanli2** [comment]
I found the example have something wrong when i try to use it to set the sample rate for my project.
1,new zipkin.CountingSampler(0.01) should be new zipkin.sampler.CountingSampler(0.01)
2,missing two ","

**Comment by adriancole** [comment]
thanks, do you mind fixing it? (raise a pull request by editing the
incorrect file)

**Comment by huanli2** [comment]
pull request:
https://github.com/openzipkin/zipkin-js/pull/76

actually, when I debug into the tracer code, and the sample rate can print correctly, but this configuration doesn't work with my express + zipkin-instrumentation-express.

"It may be the case that such libraries will turn-up, similar to how dropwizard-zipkin was made in java to bind dropwizard-style config on top of brave."  do you have a release date or have a plan to fix it?

**Comment by nickcodefresh** [comment]
Thanks guys, works a treat
