### ISSUE TITLE
upstream security vulnerabilities in `ws`

### ISSUE THREAD

**Issue by jondb** [openzipkin/zipkin-js#93]
Hi - you're using `thrift` and `thrift` is using `ws`. `thrift` has not patched an old security vulnerability in `ws`. 

https://nodesecurity.io/advisories/120 and https://nodesecurity.io/advisories/67

Thrift has an issue here: https://issues.apache.org/jira/browse/THRIFT-4064

Any chance you can urge thrift to patch?

**Comment by eirslett** [comment]
Things happen slowly at upstream thrift. I think the best thing zipkin users can do, is to pin the version of ws. zipkin-js isn't using ws, or using the part of thrift that is using ws.
