### ISSUE TITLE
sampler

### ISSUE THREAD

**Issue by yzfshuijing** [openzipkin/zipkin-js#94]
function makeCountingEvaluator(sampleRate) {
  if (sampleRate <= 0) {
    return neverSample;
  } else if (sampleRate >= 1) {
    return alwaysSample;
  } else {
    let counter = 0;
    const limit = parseInt(1 / sampleRate);
    const counting = function counting(traceId) { // eslint-disable-line no-unused-vars
      counter = counter % limit;
      const shouldSample = counter === 0;
      counter++;
      return shouldSample;
    };
    counting.toString = () => `countingSampler: sampleRate=${sampleRate}`;
    return counting;
  }
}

In your code, if the sampleRate > 0.5, then the limit is 1, so sample rate 0.9 will not  sample 90 % of all incoming requests, otherwise it will sample 100%.
am i right?
looking forward your answer!

**Comment by eirslett** [comment]
Look at [the unit tests](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/test/sampler.test.js#L42), they document how it works.

**Comment by yzfshuijing** [comment]
thanks for your answer
I know how to use the CountingSampler, but if i want  sample 90 % of all incoming requests,
"const countingSampler = new CountingSampler(0.9); "
in your code, it will be 100%, not 90%,

**Comment by adriancole** [comment]
If thats the case, should be a bug that can be found by adding a unit test.
Are you up to making a test that shows the problem and fixing it?

**Comment by yzfshuijing** [comment]
@adriancole 
describe('CountingSampler', () => {
  it('should count, and sample every fourth sample (sample rate 0.8)', () => {
    const sampler = new CountingSampler(0.8);
    const s = () => sampler.shouldSample(makeTestTraceId({}));

    const sampled = [s(), s(), s(), s(), s(), s(), s(), s(), s(), s()];
    const expected = [T, T, T, T, T, T, T, T, T, T];

    expect(sampled).to.deep.equal(expected);
  });
});
this will test the result
but I have not find a good way to solve the problem

**Comment by yzfshuijing** [comment]
@adriancole  
you can see the source code 
function makeCountingEvaluator(sampleRate) {
if (sampleRate <= 0) {
return neverSample;
} else if (sampleRate >= 1) {
return alwaysSample;
} else {
let counter = 0;
const limit = parseInt(1 / sampleRate);
const counting = function counting(traceId) { // eslint-disable-line no-unused-vars
counter = counter % limit;
const shouldSample = counter === 0;
counter++;
return shouldSample;
};
counting.toString = () => countingSampler: sampleRate=${sampleRate};
return counting;
}
}

if the rate > 0.5, then the logic is wrong  or even if (1 % rate != 0), the sample result is not accurate

**Comment by adriancole** [comment]
No offence but i think this issue is being over discussed. If there is an
obvious bug just needs someone to fix it. If you cant fix it, then just
need someone else to.
